import walk from 'walk-sync'
import { existsSync, lstatSync, unlinkSync } from 'fs'
import path from 'path'
import { mkdir, rm, readFile, writeFile, readdir } from 'fs/promises'
import matter from '@gr2m/gray-matter'
import { difference, isEqual } from 'lodash-es'

import { allVersions } from '@/versions/lib/all-versions'
import getApplicableVersions from '@/versions/lib/get-applicable-versions'
import { createLogger } from '@/observability/logger'
import type { MarkdownFrontmatter } from '@/types'

const logger = createLogger(import.meta.url)

type FrontmatterData = Partial<MarkdownFrontmatter> & {
  autogenerated?: string
  [key: string]: unknown
}

type SourceContentItem = {
  data: FrontmatterData
  content: string
}

type SourceContent = {
  [key: string]: SourceContentItem
}

type IndexOrder = {
  [key: string]: {
    startsWith?: string[]
  }
}

type UpdateContentDirectoryOptions = {
  targetDirectory: string
  sourceContent: SourceContent
  frontmatter: FrontmatterData
  indexOrder?: IndexOrder
}

type UpdateDirectoryOptions = {
  rootDirectoryOnly?: boolean
  shortTitle?: boolean
  indexOrder?: IndexOrder
}

type ChildUpdates = {
  itemsToAdd: string[]
  itemsToRemove: string[]
}

type DirectoryInfo = {
  directoryContents: string[]
  directoryFiles: string[]
  childDirectories: string[]
}

type ChildrenComparison = {
  childrenOnDisk: string[]
  indexChildren: string[]
}

const ROOT_INDEX_FILE = 'content/index.md'
export const MARKDOWN_COMMENT = '\n<!-- Content after this section is automatically generated -->\n'

export async function updateContentDirectory({
  targetDirectory,
  sourceContent,
  frontmatter,
  indexOrder,
}: UpdateContentDirectoryOptions): Promise<void> {
  const sourceFiles = Object.keys(sourceContent)
  await createDirectory(targetDirectory)
  await removeMarkdownFiles(targetDirectory, sourceFiles, frontmatter.autogenerated)
  await updateMarkdownFiles(targetDirectory, sourceContent, frontmatter, indexOrder)
}

async function removeMarkdownFiles(
  targetDirectory: string,
  sourceFiles: string[],
  autogeneratedType: string | undefined,
): Promise<void> {
  const autogeneratedFiles = await getAutogeneratedFiles(targetDirectory, autogeneratedType)
  const filesToRemove = difference(autogeneratedFiles, sourceFiles)
  if (filesToRemove.length > 0) {
    logger.info('Removing stale markdown files', {
      targetDirectory,
      count: filesToRemove.length,
    })
  }
  for (const file of filesToRemove) {
    unlinkSync(file)
  }
}

async function getAutogeneratedFiles(
  targetDirectory: string,
  autogeneratedType: string | undefined,
): Promise<string[]> {
  const files = walk(targetDirectory, {
    includeBasePath: true,
    directories: false,
    globs: ['**/*.md'],
    ignore: ['**/README.md', '**/index.md'],
  })
  return (
    await Promise.all(
      files.map(async (file: string) => {
        const { data } = matter(await readFile(file, 'utf-8'))
        if (data.autogenerated === autogeneratedType) {
          return file
        }
      }),
    )
  ).filter(Boolean) as string[]
}

async function updateMarkdownFiles(
  targetDirectory: string,
  sourceContent: SourceContent,
  frontmatter: FrontmatterData,
  indexOrder: IndexOrder = {},
): Promise<void> {
  for (const [file, newContent] of Object.entries(sourceContent)) {
    await updateMarkdownFile(file, newContent.data, newContent.content)
  }
  await updateDirectory(targetDirectory, frontmatter, { indexOrder })
  // Update only the parent index because pipelines must not touch sibling directories.
  await updateDirectory(path.dirname(targetDirectory), frontmatter, { rootDirectoryOnly: true })
}

// Existing autogenerated pages keep writer-edited frontmatter except versions.
// New pages use source frontmatter because no writer edits exist yet.
async function updateMarkdownFile(
  file: string,
  sourceData: FrontmatterData,
  sourceContent: string,
  commentDelimiter: string = MARKDOWN_COMMENT,
): Promise<void> {
  if (existsSync(file)) {
    const { data, content } = matter(await readFile(file, 'utf-8'))

    // Multiple delimiters make the writer-owned and generated content split unsafe.
    const matcher = new RegExp(commentDelimiter, 'g')
    const matches = content.match(matcher)
    if (matches && matches.length > 1) {
      logger.error('File has multiple comment delimiters', { file })
      throw new Error(`Error: ${file} has multiple comment delimiters`)
    }

    const [manuallyCreatedContent, automatedContent] = matches
      ? content.split(commentDelimiter)
      : [content, '']

    const isDelimiterMissing = !matches
    const isContentSame = automatedContent === sourceContent
    const isVersionsSame = isEqual(sourceData.versions, data.versions)
    if (isContentSame && isVersionsSame && !isDelimiterMissing) {
      logger.debug('Markdown file unchanged, skipping', { file })
      return
    }

    logger.debug('Updating existing markdown file', {
      file,
      contentChanged: !isContentSame,
      versionsChanged: !isVersionsSame,
      delimiterMissing: isDelimiterMissing,
    })

    const newData = { ...data }
    newData.versions = sourceData.versions
    const targetContent = manuallyCreatedContent + commentDelimiter + sourceContent
    const newFileContent = appendVersionComment(matter.stringify(targetContent, newData))
    await writeFile(file, newFileContent)
  } else {
    logger.info('Creating new markdown file', { file })
    await createDirectory(path.dirname(file))
    const newFileContent = appendVersionComment(
      matter.stringify(commentDelimiter + sourceContent, sourceData),
    )
    await writeFile(file, newFileContent)
  }
}

// Call after Markdown updates and deletions because child index files mirror disk state.
async function updateDirectory(
  directory: string,
  frontmatter: FrontmatterData,
  { rootDirectoryOnly = false, shortTitle = false, indexOrder = {} }: UpdateDirectoryOptions = {},
): Promise<void> {
  const initialDirectoryListing = await getDirectoryInfo(directory)
  if (initialDirectoryListing.directoryContents.length === 0 && !rootDirectoryOnly) {
    logger.info('Removing empty directory', { directory })
    await rm(directory, { recursive: true, force: true })
    return
  }

  if (!rootDirectoryOnly) {
    await Promise.all(
      initialDirectoryListing.childDirectories.map(async (subDirectory) => {
        await updateDirectory(`${directory}/${subDirectory}`, frontmatter, { indexOrder })
      }),
    )
  }

  const indexFile = `${directory}/index.md`
  const { data, content } = await getIndexFileContents(indexFile, frontmatter, shortTitle)

  // Recursive calls may remove child directories, so read the directory again before syncing.
  const { directoryContents, childDirectories, directoryFiles } = await getDirectoryInfo(directory)

  const { childrenOnDisk, indexChildren } = getChildrenToCompare(
    indexFile,
    directoryContents,
    data.children || [],
  )

  const itemsToAdd = difference(childrenOnDisk, indexChildren)
  const itemsToRemove = difference(indexChildren, childrenOnDisk)
  if (itemsToRemove.length === 0 && itemsToAdd.length === 0) {
    logger.debug('Index children unchanged, skipping', { indexFile })
    return
  }

  if (!rootDirectoryOnly) {
    directoryFiles.push(...childDirectories.map((dir) => path.join(dir, 'index.md')))
    const newVersions = await getIndexFileVersions(directory, directoryFiles)
    const isVersionEqual = isEqual(newVersions, data.versions)
    if (!isVersionEqual) {
      data.versions = newVersions
    }
  }

  const dataUpdatedChildren = updateIndexChildren(
    data,
    { itemsToAdd, itemsToRemove },
    indexFile,
    indexOrder,
    isRootIndexFile(indexFile),
  )

  await writeFile(indexFile, matter.stringify(content, dataUpdatedChildren))
}

// Root index children omit the leading slash; other index.md children include it.
// Disk entries include extensions, so normalize both sides before comparing them.
function getChildrenToCompare(
  indexFile: string,
  directoryContents: string[],
  fmChildren: string[] | undefined,
): ChildrenComparison {
  if (!fmChildren) {
    logger.error('No children property found in index file', { indexFile })
    throw new Error(`No children property found in ${indexFile}`)
  }

  const isEarlyAccess = (item: string) => isRootIndexFile(indexFile) && item === 'early-access'

  const childrenOnDisk = directoryContents
    .map((file) => `${path.basename(file, '.md')}`)
    .filter((item) => !isEarlyAccess(item))

  const indexChildren = fmChildren
    .map((child) => child.replace('/', ''))
    .filter((item) => !isEarlyAccess(item))

  return { childrenOnDisk, indexChildren }
}

// Autogenerated indexes use config startsWith ordering first, then alphabetical entries.
// Manual indexes keep existing order and append new children to the end.
function updateIndexChildren(
  data: FrontmatterData,
  childUpdates: ChildUpdates,
  indexFile: string,
  indexOrder: IndexOrder,
  rootIndex: boolean = false,
): FrontmatterData {
  const { itemsToAdd, itemsToRemove } = childUpdates
  const childPrefix = rootIndex ? '' : '/'

  const children = [...(data.children || [])]
    .map((item) => item.replace(childPrefix, ''))
    .filter((item) => !itemsToRemove.includes(item))
  children.push(...itemsToAdd)

  const orderedIndexChildren: string[] = []

  // Tests run content in a temp directory, so config keys need repo-relative index paths.
  const indexRelativePath = process.env.TEST_OS_ROOT_DIR
    ? indexFile.replace(`${process.env.TEST_OS_ROOT_DIR}/`, '')
    : indexFile

  const indexOrderConfig = indexOrder[indexRelativePath]
  const isAutogenerated = data.autogenerated
  if (indexOrderConfig && isAutogenerated) {
    if (indexOrderConfig.startsWith) {
      const sortableChildren = difference(children, indexOrderConfig.startsWith).sort()
      orderedIndexChildren.push(...indexOrderConfig.startsWith, ...sortableChildren)
    }
  } else if (isAutogenerated) {
    orderedIndexChildren.push(...children)
    orderedIndexChildren.sort()
  } else {
    // Manual index files keep writer-defined ordering.
    orderedIndexChildren.push(...children)
  }

  const updatedData = { ...data }
  updatedData.children = orderedIndexChildren.map((item) => `${childPrefix}${item}`)

  return updatedData
}

async function getIndexFileContents(
  indexFile: string,
  frontmatter: FrontmatterData,
  shortTitle: boolean = false,
): Promise<{ data: FrontmatterData; content: string }> {
  const directory = path.dirname(indexFile)
  const indexFileContent = {
    data: {
      title: path.basename(directory),
      ...frontmatter,
      children: [],
    },
    content: '',
  }
  if (shortTitle) {
    indexFileContent.data.shortTitle = path.basename(directory)
  }

  return existsSync(indexFile) ? matter(await readFile(indexFile, 'utf-8')) : indexFileContent
}

async function getIndexFileVersions(
  directory: string,
  files: string[],
): Promise<{ [key: string]: string }> {
  const versions = new Set<string>()
  await Promise.all(
    files.map(async (file) => {
      const filepath = path.join(directory, file)
      if (!existsSync(filepath)) {
        logger.error('File does not exist while assembling index versions', { filepath })
        throw new Error(
          `File ${filepath} does not exist while assembling directory index.md files to create parent version.`,
        )
      }
      if (!file.endsWith('.md') && !file.endsWith('.mdx')) {
        return
      }
      const { data } = matter(await readFile(filepath, 'utf-8'))
      if (!data || !data.versions) {
        logger.error('Frontmatter missing versions', { filepath })
        throw new Error(`Frontmatter in ${filepath} does not contain versions.`)
      }
      const fmVersions = getApplicableVersions(data.versions)
      for (const version of fmVersions) {
        versions.add(version)
      }
    }),
  )
  const versionArray = [...versions]
  return await convertVersionsToFrontmatter(versionArray)
}

// Converts applicable versions to versions frontmatter.
// Example: free-pro-team@latest, enterprise-cloud@latest, and every supported GHES release
// become fpt: *, ghec: *, and ghes: *.
export async function convertVersionsToFrontmatter(
  versions: string[],
): Promise<{ [key: string]: string }> {
  const frontmatterVersions: { [key: string]: string } = {}
  const numberedReleases: { [key: string]: { availableReleases: (string | undefined)[] } } = {}

  // GHES uses semantic version ranges because it has numbered releases.
  for (const version of versions) {
    const docsVersion = allVersions[version]
    if (!docsVersion.hasNumberedReleases) {
      frontmatterVersions[docsVersion.shortName] = '*'
    } else {
      // Track supported GHES releases by position so gaps become explicit ranges later.
      const i = docsVersion.releases.indexOf(docsVersion.currentRelease)
      if (!numberedReleases[docsVersion.shortName]) {
        const availableReleases: (string | undefined)[] = Array(docsVersion.releases.length).fill(
          undefined,
        )
        availableReleases[i] = docsVersion.currentRelease
        numberedReleases[docsVersion.shortName] = {
          availableReleases,
        }
      } else {
        numberedReleases[docsVersion.shortName].availableReleases[i] = docsVersion.currentRelease
      }
    }
  }

  for (const key of Object.keys(numberedReleases)) {
    const availableReleases = numberedReleases[key].availableReleases
    const versionContinuity = checkVersionContinuity(availableReleases)
    if (availableReleases.every(Boolean)) {
      frontmatterVersions[key] = '*'
    } else if (!versionContinuity) {
      // Gapped releases must enumerate each supported version, such as =3.3 || =3.5.
      const semVer = availableReleases
        .filter(Boolean)
        .map((release) => `=${release}`)
        .join(' || ')
      frontmatterVersions[key] = semVer
    } else {
      const semVer: string[] = []
      if (!availableReleases[availableReleases.length - 1]) {
        const startVersion = availableReleases.filter(Boolean).pop()
        semVer.push(`>=${startVersion}`)
      }
      if (!availableReleases[0]) {
        const endVersion = availableReleases.filter(Boolean).shift()
        semVer.push(`<=${endVersion}`)
      }
      frontmatterVersions[key] = semVer.join(' ')
    }
  }
  const sortedFrontmatterVersions = Object.keys(frontmatterVersions)
    .sort()
    .reduce((acc: { [key: string]: string }, key) => {
      acc[key] = frontmatterVersions[key]
      return acc
    }, {})
  return sortedFrontmatterVersions
}

// A gap between supported versions, such as 3.2 and 3.4 without 3.3, needs a custom range.
function checkVersionContinuity(versions: (string | undefined)[]): boolean {
  const availableVersions = [...versions]

  // Missing values at the ends mark normal range boundaries, not gaps.
  while (!availableVersions[0]) {
    availableVersions.shift()
  }
  while (!availableVersions[availableVersions.length - 1]) {
    availableVersions.pop()
  }
  return availableVersions.every(Boolean)
}

function isRootIndexFile(indexFile: string): boolean {
  return indexFile === ROOT_INDEX_FILE
}

async function createDirectory(targetDirectory: string): Promise<void> {
  if (!existsSync(targetDirectory)) {
    await mkdir(targetDirectory, { recursive: true })
  }
}

async function getDirectoryInfo(directory: string): Promise<DirectoryInfo> {
  if (!existsSync(directory)) {
    logger.error('Directory does not exist', { directory })
    throw new Error(`Directory ${directory} did not exist when attempting to get directory info.`)
  }
  const directoryContents = (await readdir(directory)).filter(
    (file) => file !== 'README.md' && file !== 'index.md',
  )

  const childDirectories = directoryContents.filter((item) =>
    lstatSync(`${directory}/${item}`).isDirectory(),
  )

  const directoryFiles = difference(directoryContents, childDirectories)
  return { directoryContents, directoryFiles, childDirectories }
}

function appendVersionComment(stringifiedContent: string): string {
  return stringifiedContent.replace(
    '\nversions:\n',
    `\nversions: # DO NOT MANUALLY EDIT. CHANGES WILL BE OVERWRITTEN BY A 🤖\n`,
  )
}
