//
// Generates the llms.txt content for github.com from popularity data
// and the docs page catalog. Run via:
//
//   npx tsx src/workflows/generate-llms-txt.ts > llms.txt
//
// Requires DOCS_BOT_PAT_BASE for fetching popularity data from
// github/docs-internal-data.
//

import { loadPageMap } from '@/frame/lib/page-data'
import { renderContent } from '@/content-render/index'
import { getDataByLanguage } from '@/data-directory/lib/get-data'
import { allVersions } from '@/versions/lib/all-versions'
import type { Page, Context } from '@/types'

// =====================================================================
// Configuration — edit these to change what appears in llms.txt
// =====================================================================

export const ROLLUP_URL =
  'https://raw.githubusercontent.com/github/docs-internal-data/main/hydro/rollups/pageviews/en/free-pro-team/rollup.json'
export const TOP_N = 100
export const SMALL_CATEGORY_THRESHOLD = 3
const BASE_URL = 'https://docs.github.com'
const BASE_API_URL = 'https://docs.github.com/api'

// early-access MUST stay excluded — never expose internal content.
export const EXCLUDED_CATEGORIES = new Set([
  'communities',
  'contributing',
  'early-access',
  'education',
  'enterprise-onboarding',
  'integrations',
  'nonprofit',
  'search',
  'site-policy',
  'subscriptions-and-notifications',
  'support',
  'video-transcripts',
])

export const EXCLUDED_SLUGS = new Set(['index'])

// Pinned pages for coding agents and automation — always included
// regardless of popularity. Edit this list to add or remove pages.
export const PINNED_PAGES = [
  'copilot/how-tos/provide-context/use-mcp/extend-copilot-chat-with-mcp',
  'copilot/how-tos/provide-context/use-mcp/use-the-github-mcp-server',
  'copilot/how-tos/provide-context/use-mcp/set-up-the-github-mcp-server',
  'copilot/how-tos/use-copilot-agents/coding-agent/about-coding-agent',
  'copilot/how-tos/use-copilot-agents/coding-agent/create-custom-agents',
  'github-cli/github-cli',
  'github-cli/github-cli/quickstart',
  'rest',
  'graphql',
  'actions',
]

// =====================================================================
// Header and API section text — easy to edit for writers
// =====================================================================

const HEADER = `\
# GitHub

> GitHub is a developer platform for building, shipping, and \
maintaining software. It provides cloud-based Git repository hosting, \
CI/CD via GitHub Actions, project management with Issues and Projects, \
code review via pull requests, AI-powered development with GitHub \
Copilot, and APIs (REST and GraphQL) for automation and integration.

GitHub documentation is available at ${BASE_URL}. The content covers \
GitHub.com (cloud), GitHub Enterprise Server, and GitHub Enterprise Cloud.`

const API_SECTION = `\
## Programmatic access (retrieve markdown via APIs instead of parsing HTML)

To retrieve full article content, page lists, or search results \
programmatically, please use the APIs below. These APIs return \
structured markdown and JSON and are the preferred way for LLMs and \
automated tools to access GitHub documentation.

- [Page List API](${BASE_API_URL}/pagelist/en/free-pro-team@latest): \
Returns every docs page path for a given language and version
- [Article API](${BASE_API_URL}/article): \
Returns the full rendered content of any docs page as markdown. \
Example: \`curl "${BASE_API_URL}/article?pathname=/en/get-started/start-your-journey/about-github-and-git"\`
- [Search API](${BASE_API_URL}/search): \
Search across all docs content. \
Example: \`curl "${BASE_API_URL}/search?query=actions&language=en&version=free-pro-team@latest"\``

const PINNED_SECTION_HEADING = 'Building with GitHub (for coding agents and automation)'
const MORE_PAGES_HEADING = 'More pages'

const AUTO_UPDATE_COMMENT = `\
<!-- This file is automatically generated. Do not edit manually. -->`

// =====================================================================
// Types
// =====================================================================

export type Rollup = Record<string, number>
export type PageMap = Record<string, Page>

// =====================================================================
// Data loading
// =====================================================================

export async function fetchRollup(): Promise<Rollup> {
  const token = process.env.DOCS_BOT_PAT_BASE
  if (!token) throw new Error('DOCS_BOT_PAT_BASE is required')
  const res = await fetch(ROLLUP_URL, {
    headers: {
      Accept: 'application/vnd.github.raw+json',
      Authorization: `token ${token}`,
    },
  })
  if (!res.ok)
    throw new Error(`Failed to fetch rollup: ${res.status} ${res.statusText} (${ROLLUP_URL})`)
  return (await res.json()) as Rollup
}

// =====================================================================
// Liquid rendering
// =====================================================================

const renderContext: Context = {
  currentLanguage: 'en',
  currentVersion: 'free-pro-team@latest',
  currentVersionObj: allVersions['free-pro-team@latest'],
  getDottedData: (path: string) => getDataByLanguage(path, 'en'),
} as Context

export async function renderLiquid(template: string): Promise<string> {
  if (!template || (!template.includes('{%') && !template.includes('{{'))) return template
  const html = await renderContent(template, renderContext, { textOnly: true })
  return html.replace(/^<p>|<\/p>$/g, '').trim()
}

// =====================================================================
// Helpers
// =====================================================================

export function pageExists(pagePath: string, pages: PageMap): boolean {
  return `/en/${pagePath}` in pages
}

export async function getPageTitle(permalink: string, pages: PageMap): Promise<string> {
  const page = pages[permalink]
  const raw = page?.shortTitle || page?.title || ''
  if (!raw) return titleCase(permalink.split('/').pop() || '')
  const rendered = await renderLiquid(raw)
  return rendered.replace(/ documentation$/i, '')
}

export async function getPageIntro(permalink: string, pages: PageMap): Promise<string | null> {
  const page = pages[permalink]
  const raw = page?.intro || ''
  if (!raw) return null
  return renderLiquid(raw)
}

export async function formatPageLine(pagePath: string, pages: PageMap): Promise<string> {
  const permalink = `/en/${pagePath}`
  const title =
    (await getPageTitle(permalink, pages)) || titleCase(pagePath.split('/').pop() || pagePath)
  const intro = await getPageIntro(permalink, pages)
  if (intro) return `- [${title}](${BASE_URL}${permalink}): ${intro}`
  return `- [${title}](${BASE_URL}${permalink})`
}

export function titleCase(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

// =====================================================================
// Main generation
// =====================================================================

export async function generate(pages: PageMap, rollup: Rollup): Promise<string> {
  const pinnedSet = new Set(PINNED_PAGES)
  const topPages = Object.entries(rollup)
    .filter(
      ([path]) =>
        path &&
        !EXCLUDED_SLUGS.has(path) &&
        !EXCLUDED_CATEGORIES.has(path.split('/')[0]) &&
        !pinnedSet.has(path) &&
        pageExists(path, pages),
    )
    .sort((a, b) => b[1] - a[1])
    .slice(0, TOP_N)

  // Group by category, alphabetical within each
  const categoryMap = new Map<string, string[]>()
  for (const [pagePath] of topPages) {
    const category = pagePath.split('/')[0]
    const list = categoryMap.get(category) ?? []
    list.push(pagePath)
    categoryMap.set(category, list)
  }
  for (const [, list] of categoryMap) list.sort()
  const categories = new Map(
    [...categoryMap.entries()].sort(
      (a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]),
    ),
  )

  const sections: string[] = [HEADER, '', API_SECTION, '']

  // Pinned section
  const existingPinned = PINNED_PAGES.filter((p) => pageExists(p, pages))
  if (existingPinned.length > 0) {
    sections.push(`## ${PINNED_SECTION_HEADING}`, '')
    for (const p of existingPinned) sections.push(await formatPageLine(p, pages))
    sections.push('')
  }

  // Large and small categories
  const largeCategories: [string, string[]][] = []
  const smallCategoryPages: string[] = []
  for (const [cat, catPages] of categories) {
    if (catPages.length < SMALL_CATEGORY_THRESHOLD) smallCategoryPages.push(...catPages)
    else largeCategories.push([cat, catPages])
  }
  smallCategoryPages.sort()

  for (const [cat, catPages] of largeCategories) {
    const title = (await getPageTitle(`/en/${cat}`, pages)) || titleCase(cat)
    sections.push(`## ${title}`, '')
    const intro = await getPageIntro(`/en/${cat}`, pages)
    if (intro) sections.push(`> ${intro}`, '')
    for (const p of catPages) sections.push(await formatPageLine(p, pages))
    sections.push('')
  }

  if (smallCategoryPages.length > 0) {
    sections.push(`## ${MORE_PAGES_HEADING}`, '')
    for (const p of smallCategoryPages) sections.push(await formatPageLine(p, pages))
    sections.push('')
  }

  sections.push(AUTO_UPDATE_COMMENT)
  return sections.join('\n')
}

// =====================================================================
// Entry point
// =====================================================================

async function main() {
  const pages = await loadPageMap(undefined, ['en'])
  const rollup = await fetchRollup()
  const content = await generate(pages, rollup)
  process.stdout.write(content)
}

// Only run when executed directly, not when imported for testing
const isEntryPoint =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith('generate-llms-txt.ts')

if (isEntryPoint) {
  try {
    await main()
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}
