import type { Response, NextFunction } from 'express'

import type { ExtendedRequest, Context, Tree, ToC } from '@/types'
import findPageInSiteTree from '@/frame/lib/find-page-in-site-tree.js'

// This module adds either flatTocItems or nestedTocItems to the context object for
// product, category, and map topic TOCs that don't have other layouts specified.
// They are rendered by includes/generic-toc-flat.html or includes/generic-toc-nested.html.
export default async function genericToc(req: ExtendedRequest, res: Response, next: NextFunction) {
  if (!req.context) throw new Error('request not contextualized')
  if (!req.context.page) return next()
  if (req.context.currentLayoutName !== 'default') return next()
  // This middleware can only run on product, category, and map topics.
  if (
    req.context.page.documentType === 'homepage' ||
    req.context.page.documentType === 'article' ||
    req.context.page.relativePath === 'search/index.md'
  )
    return next()

  // This one product TOC is weird.
  const isOneOffProductToc = req.context.page.relativePath === 'github/index.md'

  // There are different types of TOC depending on the document type.
  const tocTypes: Record<string, string> = {
    product: 'flat',
    category: 'nested',
    mapTopic: 'flat',
  }

  // Frontmatter can optionally be set on an Early Access product to show hidden child items.
  // If so, this is a special case where we want to override the flat tocType and use a nested type.
  const earlyAccessToc = req.context.page.earlyAccessToc

  if (!req.context.currentProductTree) throw new Error('currentProductTree not in context')
  if (!req.context.currentEnglishTree) throw new Error('currentEnglishTree not in context')
  if (!req.pagePath) throw new Error('pagePath not in request')

  // Find the part of the site tree that corresponds to the current path.
  const treePage = findPageInSiteTree(
    req.context.currentProductTree,
    req.context.currentEnglishTree,
    req.pagePath,
  )

  let fauxMapTopic = false
  if (req.context.page.documentType === 'category' && req.context.page.autogenerated !== 'rest') {
    // But does *have* children?
    const hasGrandchildren = (treePage.childPages || []).some((child) => child.children)
    fauxMapTopic = !hasGrandchildren
  }

  // Find the current TOC type based on the current document type.
  const currentTocType = earlyAccessToc
    ? 'nested'
    : fauxMapTopic
      ? 'flat'
      : tocTypes[req.context.page.documentType]

  // By default, only include hidden child items on a TOC page if it's an Early Access category or
  // map topic page, not a product or 'articles' fake category page (e.g., /early-access/github/articles).
  // This is because we don't want entire EA product TOCs to be publicly browseable, but anything at the category
  // or below level is fair game because that content is scoped to specific features.
  const isCategoryOrMapTopic =
    req.context.page.documentType === 'category' || req.context.page.documentType === 'mapTopic'
  if (!req.context.currentPath) throw new Error('currentPath not in context')
  const isEarlyAccess = req.context.currentPath.includes('/early-access/')
  const isArticlesCategory = req.context.currentPath.endsWith('/articles')

  const includeHidden =
    earlyAccessToc || (isCategoryOrMapTopic && isEarlyAccess && !isArticlesCategory)

  // Conditionally run getTocItems() recursively.
  let isRecursive
  // Conditionally render intros.
  let renderIntros

  // Get an array of child links with intros and add it to the context object.
  if (currentTocType === 'flat' && !isOneOffProductToc) {
    isRecursive = false
    renderIntros = true
    req.context.genericTocFlat = await getTocItems(treePage, req.context, {
      recurse: isRecursive,
      renderIntros,
      includeHidden,
    })
  }

  // Get an array of child map topics and their child articles and add it to the context object.
  if (currentTocType === 'nested' || isOneOffProductToc) {
    isRecursive = !isOneOffProductToc
    renderIntros = false
    req.context.genericTocNested = await getTocItems(treePage, req.context, {
      recurse: isRecursive,
      renderIntros,
      includeHidden,
    })
  }

  return next()
}

// Return a nested object that contains the bits and pieces we need
// for the tree which is used for sidebars and listing
type Options = {
  recurse: boolean
  renderIntros: boolean
  includeHidden: boolean
}

async function getTocItems(node: Tree, context: Context, opts: Options): Promise<ToC[]> {
  // Cleaner than trying to be too terse inside the `.filter()` inline callback.
  function filterHidden(child: Tree): boolean {
    return opts.includeHidden || !child.page.hidden
  }

  return await Promise.all(
    node.childPages.filter(filterHidden).map(async (child) => {
      const { page } = child
      const title = await page.renderProp('rawTitle', context, { textOnly: true })
      let intro = null
      if (opts.renderIntros) {
        intro = ''
        if (page.rawIntro) {
          // The intro can contain Markdown even though it might not
          // contain any Liquid.
          // Deliberately don't use `textOnly:true` here because we intend
          // to display the intro, in a table of contents component,
          // with the HTML (dangerouslySetInnerHTML).
          intro = await page.renderProp('rawIntro', context)
        }
      }

      let childTocItems = null
      if (opts.recurse) {
        childTocItems = []
        if (child.childPages) {
          childTocItems.push(...(await getTocItems(child, context, opts)))
        }
      }

      const fullPath = child.href
      return {
        title,
        fullPath,
        intro,
        childTocItems,
      } as ToC
    }),
  )
}
