****Full Changelog**: https://github.com/tr4200812/hubhub/compare/v1.0.1...Tt

## What's Changed
* M2 by @tr4200812 in https://github.com/tr4200812/hubhub/pull/345
* Update issue templates by @tr4200812 in https://github.com/tr4200812/hubhub/pull/417
* Revert "Update issue templates" by @tr4200812 in https://github.com/tr4200812/hubhub/pull/424
* Update issue templates by @tr4200812 in https://github.com/tr4200812/hubhub/pull/431
* Revert "Update issue templates" by @tr4200812 in https://github.com/tr4200812/hubhub/pull/435
* Revert "Revert "Update issue templates"" by @tr4200812 in https://github.com/tr4200812/hubhub/pull/436
* Update next.config.js by @tr4200812 in https://github.com/tr4200812/hubhub/pull/452


**Full Changelog**: https://github.com/tr4200812/hubhub/compare/commented...TtrFull Changelog**: https://github.com/tr4200812/hubhub/compare/v1.0.1...Tt

## What's Changed
* M2 by @tr4200812 in https://github.com/tr4200812/hubhub/pull/345
* Update issue templates by @tr4200812 in https://github.com/tr4200812/hubhub/pull/417
* Revert "Update issue templates" by @tr4200812 in https://github.com/tr4200812/hubhub/pull/424
* Update issue templates by @tr4200812 in https://github.com/tr4200812/hubhub/pull/431
* Revert "Update issue templates" by @tr4200812 in https://github.com/tr4200812/hubhub/pull/435
* Revert "Revert "Update issue templates"" by @tr4200812 in https://github.com/tr4200812/hubhub/pull/436
* Update next.config.js by @tr4200812 in https://github.com/tr4200812/hubhub/pull/452


**Full Changelog**: https://github.com/tr4200812/hubhub/compare/commented...Ttr
