import { tmpdir } from 'os'
import { mkdtemp, rm, mkdir, writeFile, readFile, readdir } from 'fs/promises'
import { existsSync } from 'fs'
import path from 'path'

import { afterEach, beforeEach, describe, expect, test } from 'vitest'
import matter from '@gr2m/gray-matter'

import { MARKDOWN_COMMENT } from '@/automated-pipelines/lib/update-markdown'
import {
  syncCategoryContentFiles,
  type CategoryPresence,
} from '../scripts/utils/sync-category-content'

const FPT = 'free-pro-team@latest'
const GHEC = 'enterprise-cloud@latest'

const REFERENCE_DIR = path.join('content', 'graphql', 'reference')

// The full set of categories present in a steady-state fixture. Returned as a
// fresh Map each call so tests never share mutable state.
function steadyPresence(): CategoryPresence {
  return new Map([
    ['actions', new Set([FPT, GHEC])],
    ['sponsors', new Set([FPT])],
    ['other', new Set([FPT, GHEC])],
    ['code-scanning', new Set([FPT, GHEC])],
  ])
}

// Write an autogenerated category page with the given versions frontmatter.
async function writeCategoryFile(
  root: string,
  cat: string,
  versions: Record<string, string>,
  extra: Record<string, unknown> = {},
) {
  const data = {
    title: cat,
    shortTitle: cat,
    intro: `Reference documentation for GraphQL schema types in the ${cat} category.`,
    versions,
    autogenerated: 'graphql',
    category: ['Explore the schema reference'],
    ...extra,
  }
  await writeFile(
    path.join(root, REFERENCE_DIR, `${cat}.md`),
    matter.stringify(MARKDOWN_COMMENT, data),
  )
}

async function writeIndex(root: string, children: string[], redirectFrom: string[]) {
  const data = {
    title: 'Reference',
    redirect_from: redirectFrom,
    versions: { fpt: '*', ghec: '*', ghes: '*' },
    children,
    autogenerated: 'graphql',
  }
  await writeFile(
    path.join(root, REFERENCE_DIR, 'index.md'),
    matter.stringify(MARKDOWN_COMMENT, data),
  )
}

async function readIndex(root: string) {
  return matter(await readFile(path.join(root, REFERENCE_DIR, 'index.md'), 'utf8'))
}

async function snapshotReferenceDir(root: string): Promise<Record<string, string>> {
  const dir = path.join(root, REFERENCE_DIR)
  const files = await readdir(dir)
  const snapshot: Record<string, string> = {}
  for (const file of files.sort()) {
    snapshot[file] = await readFile(path.join(dir, file), 'utf8')
  }
  return snapshot
}

describe('syncCategoryContentFiles', () => {
  let root: string
  let contentDir: string

  beforeEach(async () => {
    root = await mkdtemp(path.join(tmpdir(), 'graphql-category-content-'))
    await mkdir(path.join(root, REFERENCE_DIR), { recursive: true })
    contentDir = path.join(root, REFERENCE_DIR)
  })

  afterEach(async () => {
    await rm(root, { recursive: true, force: true })
  })

  test('deletes emptied categories, narrows versions, and reconciles redirects', async () => {
    await writeIndex(
      root,
      ['/actions', '/sponsors', '/code-scanning', '/other'],
      ['/v4/reference', '/graphql/reference/queries'],
    )
    await writeCategoryFile(root, 'actions', { fpt: '*', ghec: '*' })
    await writeCategoryFile(root, 'sponsors', { fpt: '*', ghec: '*' })
    await writeCategoryFile(root, 'code-scanning', { fpt: '*', ghec: '*' })
    await writeCategoryFile(root, 'other', { fpt: '*', ghec: '*' })

    const presence = steadyPresence()
    presence.delete('code-scanning') // emptied -> absent in all versions

    await syncCategoryContentFiles(presence, { contentDir })

    // Emptied category file is deleted; populated ones remain.
    expect(existsSync(path.join(root, REFERENCE_DIR, 'code-scanning.md'))).toBe(false)
    expect(existsSync(path.join(root, REFERENCE_DIR, 'actions.md'))).toBe(true)
    expect(existsSync(path.join(root, REFERENCE_DIR, 'other.md'))).toBe(true)

    // Versions are narrowed to where the category actually has types.
    const sponsors = matter(await readFile(path.join(root, REFERENCE_DIR, 'sponsors.md'), 'utf8'))
    expect(sponsors.data.versions).toEqual({ fpt: '*' })

    const index = await readIndex(root)
    // Sidebar children drop the emptied category.
    expect(index.data.children).not.toContain('/code-scanning')
    expect(index.data.children).toContain('/actions')
    expect(index.data.children).toContain('/sponsors')
    expect(index.data.children).toContain('/other')

    // Disappeared category gets a root redirect; unrelated redirects are kept;
    // present categories are never redirected.
    expect(index.data.redirect_from).toContain('/graphql/reference/code-scanning')
    expect(index.data.redirect_from).toContain('/v4/reference')
    expect(index.data.redirect_from).toContain('/graphql/reference/queries')
    expect(index.data.redirect_from).not.toContain('/graphql/reference/actions')
  })

  test('recreates a reappearing category and removes its stale redirect', async () => {
    // Seed the post-deletion state: code-scanning has no page and carries a
    // disappearance redirect on the index.
    await writeIndex(
      root,
      ['/actions', '/sponsors', '/other'],
      ['/v4/reference', '/graphql/reference/code-scanning'],
    )
    await writeCategoryFile(root, 'actions', { fpt: '*', ghec: '*' })
    await writeCategoryFile(root, 'sponsors', { fpt: '*' })
    await writeCategoryFile(root, 'other', { fpt: '*', ghec: '*' })

    await syncCategoryContentFiles(steadyPresence(), { contentDir })

    expect(existsSync(path.join(root, REFERENCE_DIR, 'code-scanning.md'))).toBe(true)
    const index = await readIndex(root)
    expect(index.data.children).toContain('/code-scanning')
    expect(index.data.redirect_from).not.toContain('/graphql/reference/code-scanning')
    // Unrelated redirects survive the reconciliation.
    expect(index.data.redirect_from).toContain('/v4/reference')
  })

  test('is idempotent: a second sync run makes no further changes', async () => {
    await writeIndex(root, ['/actions', '/sponsors', '/code-scanning', '/other'], ['/v4/reference'])
    await writeCategoryFile(root, 'actions', { fpt: '*', ghec: '*' })
    await writeCategoryFile(root, 'sponsors', { fpt: '*' })
    await writeCategoryFile(root, 'code-scanning', { fpt: '*', ghec: '*' })
    await writeCategoryFile(root, 'other', { fpt: '*', ghec: '*' })

    // First run establishes the canonical steady state for this presence.
    await syncCategoryContentFiles(steadyPresence(), { contentDir })
    const before = await snapshotReferenceDir(root)
    // Second run with identical input must be a no-op.
    await syncCategoryContentFiles(steadyPresence(), { contentDir })
    const after = await snapshotReferenceDir(root)

    expect(after).toEqual(before)
  })
})
