import fs from 'fs/promises'
import path from 'path'
import walk from 'walk-sync'
import matter from '@gr2m/gray-matter'
import { isEqual } from 'lodash-es'

import {
  updateContentDirectory,
  convertVersionsToFrontmatter,
} from '@/automated-pipelines/lib/update-markdown'
import { CATEGORIES, OTHER_CATEGORY, categoryTitle } from '@/graphql/lib/categories'

// Default directory holding the per-category GraphQL reference content pages.
// Overridable via options for tests; production always uses this path.
const DEFAULT_CONTENT_DIR = path.join('content', 'graphql', 'reference')
// Value of the `autogenerated` frontmatter on managed category pages. The
// content-directory helper uses this to know which files it owns (and may
// therefore delete when a category empties).
const AUTOGENERATED_TYPE = 'graphql'
// Breadcrumb category the reference pages sit under in the sidebar.
const CATEGORY_BREADCRUMB = 'Explore the schema reference'

// Maps a category slug to the set of docs version keys (e.g.
// `free-pro-team@latest`, `enterprise-server@3.22`) in which the category has
// at least one type. Built by sync.ts from the per-version buckets.
export type CategoryPresence = Map<string, Set<string>>

const categoryUrlPath = (cat: string) => `/graphql/reference/${cat}`

// Matches a bare category reference URL (no fragment), e.g.
// `/graphql/reference/code-scanning`. Kind pages like
// `/graphql/reference/queries` also match this shape but are filtered out
// because their slug is not in CATEGORIES.
const CATEGORY_URL_RE = /^\/graphql\/reference\/([a-z][a-z0-9-]*)$/

function isPresentInAnyVersion(presence: CategoryPresence, cat: string): boolean {
  return (presence.get(cat)?.size ?? 0) > 0
}

// Read the `redirect_from` of every managed category page before the content
// helper potentially deletes those files, so redirect chains aren't lost when a
// category disappears. Returns a map of category slug -> redirect_from entries.
async function captureCategoryRedirects(contentDir: string): Promise<Map<string, string[]>> {
  const captured = new Map<string, string[]>()
  let files: string[] = []
  try {
    files = walk(contentDir, {
      includeBasePath: true,
      directories: false,
      globs: ['**/*.md'],
      ignore: ['**/index.md', '**/README.md'],
    })
  } catch {
    return captured
  }
  for (const file of files) {
    try {
      const { data } = matter(await fs.readFile(file, 'utf8'))
      if (data.autogenerated !== AUTOGENERATED_TYPE) continue
      const entries = normalizeRedirects(data.redirect_from)
      if (entries.length > 0) captured.set(path.basename(file, '.md'), entries)
    } catch {
      // Unreadable/unparseable file; nothing to capture.
    }
  }
  return captured
}

function normalizeRedirects(value: unknown): string[] {
  if (Array.isArray(value)) return value.filter((v): v is string => typeof v === 'string')
  if (typeof value === 'string') return [value]
  return []
}

// Build the `sourceContent` map the content-directory helper expects:
// `{ <targetFile>: { data: <frontmatter>, content: <body> } }`. Only categories
// that are non-empty in at least one version get a page; emptied categories are
// omitted so the helper deletes their stale files.
async function buildSourceContent(presence: CategoryPresence, contentDir: string) {
  const sourceContent: Record<string, { data: Record<string, unknown>; content: string }> = {}
  for (const cat of CATEGORIES) {
    const versionsSet = presence.get(cat)
    if (!versionsSet || versionsSet.size === 0) continue
    const versions = await convertVersionsToFrontmatter([...versionsSet])
    const title = categoryTitle(cat)
    const file = path.join(contentDir, `${cat}.md`)
    // For pages that already exist, the helper only refreshes `versions` and the
    // autogenerated body, preserving any writer edits to title/intro/category.
    // These values therefore only seed brand-new category pages.
    sourceContent[file] = {
      data: {
        title,
        shortTitle: title,
        intro: `Reference documentation for GraphQL schema types in the ${title} category.`,
        versions,
        autogenerated: AUTOGENERATED_TYPE,
        category: [CATEGORY_BREADCRUMB],
      },
      content: '',
    }
  }
  return sourceContent
}

// Reconcile the reference index `redirect_from` so that a bare category URL
// redirects to the reference root when (and only when) that category is empty in
// every version. Categories present in at least one version must NOT have a
// redirect, otherwise a still-valid versioned page would be shadowed.
async function reconcileIndexRedirects(
  presence: CategoryPresence,
  capturedRedirects: Map<string, string[]>,
  indexFile: string,
): Promise<void> {
  let raw: string
  try {
    raw = await fs.readFile(indexFile, 'utf8')
  } catch {
    return
  }
  const { data, content } = matter(raw)
  const existing = normalizeRedirects(data.redirect_from)

  // Drop redirects for managed categories that are now present (e.g. a category
  // that previously emptied and has since come back). Leave kind-page redirects
  // (queries, mutations, ...) and non-category redirects (/v4/reference) intact.
  const next = existing.filter((entry) => {
    const match = CATEGORY_URL_RE.exec(entry)
    if (!match) return true
    const cat = match[1]
    if (!(CATEGORIES as readonly string[]).includes(cat)) return true
    return !isPresentInAnyVersion(presence, cat)
  })

  // Add a root redirect for every managed category that is empty in all
  // versions. `other` is always present (un-annotated types), so it never
  // disappears, but guard against it defensively.
  for (const cat of CATEGORIES) {
    if (cat === OTHER_CATEGORY) continue
    if (isPresentInAnyVersion(presence, cat)) continue
    const url = categoryUrlPath(cat)
    if (!next.includes(url)) next.push(url)
    // Preserve any redirect_from the deleted category page carried so existing
    // inbound redirect chains keep resolving.
    for (const inherited of capturedRedirects.get(cat) ?? []) {
      if (!next.includes(inherited)) next.push(inherited)
    }
  }

  if (isEqual(next, existing)) return
  data.redirect_from = next
  await fs.writeFile(indexFile, matter.stringify(content, data))
}

// Entry point used by sync.ts after it has bucketed every version. Creates,
// updates, and deletes the per-category content pages, refreshes the reference
// index children, and reconciles disappearance redirects. `contentDir` is
// overridable for tests; production uses the default reference directory.
export async function syncCategoryContentFiles(
  presence: CategoryPresence,
  options: { contentDir?: string } = {},
): Promise<void> {
  const contentDir = options.contentDir ?? DEFAULT_CONTENT_DIR
  const indexFile = path.join(contentDir, 'index.md')
  const capturedRedirects = await captureCategoryRedirects(contentDir)
  const sourceContent = await buildSourceContent(presence, contentDir)

  await updateContentDirectory({
    targetDirectory: contentDir,
    sourceContent,
    frontmatter: {
      autogenerated: AUTOGENERATED_TYPE,
      versions: { fpt: '*', ghec: '*', ghes: '*' },
    },
  })

  await reconcileIndexRedirects(presence, capturedRedirects, indexFile)
}
