import fs from 'fs/promises'
import path from 'path'
import walk from 'walk-sync'
import matter from '@gr2m/gray-matter'
import { isEqual } from 'lodash-es'

import {
  updateContentDirectory,
  convertVersionsToFrontmatter,
} from '@/automated-pipelines/lib/update-markdown'
import { CATEGORIES, OTHER_CATEGORY, categoryTitle } from '@/graphql/lib/categories'

// Tests can override the content directory; production uses content/graphql/reference.
const DEFAULT_CONTENT_DIR = path.join('content', 'graphql', 'reference')
// updateContentDirectory deletes only pages whose autogenerated frontmatter matches graphql.
const AUTOGENERATED_TYPE = 'graphql'
// Breadcrumb category the reference pages sit under in the sidebar.
const CATEGORY_BREADCRUMB = 'Explore the schema reference'

// Maps each category slug to docs version keys where at least one type exists; sync.ts builds it.
export type CategoryPresence = Map<string, Set<string>>

const categoryUrlPath = (cat: string) => `/graphql/reference/${cat}`

// CATEGORY_URL_RE matches bare category URLs like /graphql/reference/code-scanning.
// Kind pages like /graphql/reference/queries match this shape but get filtered later.
const CATEGORY_URL_RE = /^\/graphql\/reference\/([a-z][a-z0-9-]*)$/

function isPresentInAnyVersion(presence: CategoryPresence, cat: string): boolean {
  return (presence.get(cat)?.size ?? 0) > 0
}

// Capture managed category redirects before deletion so disappearance redirects keep resolving.
async function captureCategoryRedirects(contentDir: string): Promise<Map<string, string[]>> {
  const captured = new Map<string, string[]>()
  let files: string[] = []
  try {
    files = walk(contentDir, {
      includeBasePath: true,
      directories: false,
      globs: ['**/*.md'],
      ignore: ['**/index.md', '**/README.md'],
    })
  } catch {
    return captured
  }
  for (const file of files) {
    try {
      const { data } = matter(await fs.readFile(file, 'utf8'))
      if (data.autogenerated !== AUTOGENERATED_TYPE) continue
      const entries = normalizeRedirects(data.redirect_from)
      if (entries.length > 0) captured.set(path.basename(file, '.md'), entries)
    } catch {
      // Unreadable/unparseable file; nothing to capture.
    }
  }
  return captured
}

function normalizeRedirects(value: unknown): string[] {
  if (Array.isArray(value)) return value.filter((v): v is string => typeof v === 'string')
  if (typeof value === 'string') return [value]
  return []
}

// buildSourceContent omits empty categories so updateContentDirectory deletes stale pages.
async function buildSourceContent(presence: CategoryPresence, contentDir: string) {
  const sourceContent: Record<string, { data: Record<string, unknown>; content: string }> = {}
  for (const cat of CATEGORIES) {
    const versionsSet = presence.get(cat)
    if (!versionsSet || versionsSet.size === 0) continue
    const versions = await convertVersionsToFrontmatter([...versionsSet])
    const title = categoryTitle(cat)
    const file = path.join(contentDir, `${cat}.md`)
    // Managed pages keep writer-edited title, intro, and category; values apply only at creation.
    sourceContent[file] = {
      data: {
        title,
        shortTitle: title,
        intro: `Reference documentation for GraphQL schema types in the ${title} category.`,
        versions,
        autogenerated: AUTOGENERATED_TYPE,
        category: [CATEGORY_BREADCRUMB],
      },
      content: '',
    }
  }
  return sourceContent
}

// Empty categories redirect to the reference root only when every version lacks that category.
// Present categories must not redirect, or they shadow still-valid versioned pages.
async function reconcileIndexRedirects(
  presence: CategoryPresence,
  capturedRedirects: Map<string, string[]>,
  indexFile: string,
): Promise<void> {
  let raw: string
  try {
    raw = await fs.readFile(indexFile, 'utf8')
  } catch {
    return
  }
  const { data, content } = matter(raw)
  const existing = normalizeRedirects(data.redirect_from)

  // Drop redirects for categories that returned; keep kind-page and non-category redirects intact.
  const next = existing.filter((entry) => {
    const match = CATEGORY_URL_RE.exec(entry)
    if (!match) return true
    const cat = match[1]
    if (!(CATEGORIES as readonly string[]).includes(cat)) return true
    return !isPresentInAnyVersion(presence, cat)
  })

  // Add root redirects for categories empty in all versions; other never disappears.
  for (const cat of CATEGORIES) {
    if (cat === OTHER_CATEGORY) continue
    if (isPresentInAnyVersion(presence, cat)) continue
    const url = categoryUrlPath(cat)
    if (!next.includes(url)) next.push(url)
    // Carry redirect_from from deleted category pages so inbound chains keep resolving.
    for (const inherited of capturedRedirects.get(cat) ?? []) {
      if (!next.includes(inherited)) next.push(inherited)
    }
  }

  if (isEqual(next, existing)) return
  data.redirect_from = next
  await fs.writeFile(indexFile, matter.stringify(content, data))
}

// Creates, updates, and deletes category pages after sync.ts buckets every version.
// Also refreshes index children and disappearance redirects; tests can override contentDir.
export async function syncCategoryContentFiles(
  presence: CategoryPresence,
  options: { contentDir?: string } = {},
): Promise<void> {
  const contentDir = options.contentDir ?? DEFAULT_CONTENT_DIR
  const indexFile = path.join(contentDir, 'index.md')
  const capturedRedirects = await captureCategoryRedirects(contentDir)
  const sourceContent = await buildSourceContent(presence, contentDir)

  await updateContentDirectory({
    targetDirectory: contentDir,
    sourceContent,
    frontmatter: {
      autogenerated: AUTOGENERATED_TYPE,
      versions: { fpt: '*', ghec: '*', ghes: '*' },
    },
  })

  await reconcileIndexRedirects(presence, capturedRedirects, indexFile)
}
