import { describe, expect, test } from 'vitest'

import { validateCrossPageAnchors, type PendingCrossPageAnchor } from '../lib/cross-page-anchors'

function anchor(overrides: Partial<PendingCrossPageAnchor> = {}): PendingCrossPageAnchor {
  return {
    targetKey: '/en/some/target',
    fragment: 'a-heading',
    href: '/some/target#a-heading',
    file: 'content/source.md',
    line: 10,
    text: 'link text',
    ...overrides,
  }
}

describe('validateCrossPageAnchors (pass 2)', () => {
  test('returns nothing when the fragment exists on the target page', () => {
    const cache = new Map([['/en/some/target', new Set(['a-heading', 'other'])]])
    expect(validateCrossPageAnchors([anchor()], cache)).toEqual([])
  })

  test('flags a link whose fragment is missing from the target page', () => {
    const cache = new Map([['/en/some/target', new Set(['other-heading'])]])
    const broken = validateCrossPageAnchors([anchor()], cache)
    expect(broken).toEqual([
      { href: '/some/target#a-heading', file: 'content/source.md', lines: [10], text: 'link text' },
    ])
  })

  test('skips (does not flag) a target with no cache entry', () => {
    // A missing cache entry means the target resolved to a version not covered by this
    // run, or is an autogenerated page — either way it is validated elsewhere / at runtime.
    const emptyCache = new Map<string, Set<string>>()
    expect(validateCrossPageAnchors([anchor()], emptyCache)).toEqual([])
  })

  test('evaluates each anchor independently against its own target', () => {
    const cache = new Map([
      ['/en/page-a', new Set(['present'])],
      ['/en/page-b', new Set(['also-present'])],
      // /en/page-c intentionally absent from the cache
    ])
    const pending = [
      anchor({ targetKey: '/en/page-a', fragment: 'present', href: '/page-a#present' }),
      anchor({ targetKey: '/en/page-a', fragment: 'missing', href: '/page-a#missing', line: 20 }),
      anchor({ targetKey: '/en/page-b', fragment: 'also-present', href: '/page-b#also-present' }),
      anchor({ targetKey: '/en/page-c', fragment: 'whatever', href: '/page-c#whatever', line: 30 }),
    ]
    const broken = validateCrossPageAnchors(pending, cache)
    expect(broken).toEqual([
      { href: '/page-a#missing', file: 'content/source.md', lines: [20], text: 'link text' },
    ])
  })

  test('returns nothing for an empty pending list', () => {
    expect(validateCrossPageAnchors([], new Map())).toEqual([])
  })

  test('does not flag a cross-page #top link', () => {
    // Mirrors the same-page anchor exemption for `#` / `#top`. Browsers scroll to the
    // top of the document for `#top` when nothing carries that ID, so it is always
    // valid even though it never appears in the target's computed heading IDs.
    const cache = new Map([['/en/some/target', new Set(['a-heading'])]])
    const pending = [
      anchor({ fragment: 'top', href: '/some/target#top' }),
      anchor({ fragment: 'missing', href: '/some/target#missing', line: 20 }),
    ]
    expect(validateCrossPageAnchors(pending, cache)).toEqual([
      { href: '/some/target#missing', file: 'content/source.md', lines: [20], text: 'link text' },
    ])
  })
})
