import { describe, expect, test } from 'vitest'

import {
  findLinkLines,
  isAnchorCheckableTarget,
  resolveLinkKeyForVersion,
  versionFromResolvedKey,
} from '@/links/lib/page-anchors'
import type { Page } from '@/types'

describe('versionFromResolvedKey', () => {
  test('returns null for an unversioned (free-pro-team) key', () => {
    expect(versionFromResolvedKey('/en/actions/foo')).toBe(null)
  })

  test('reads an explicit enterprise-cloud prefix', () => {
    expect(versionFromResolvedKey('/en/enterprise-cloud@latest/actions/foo')).toBe(
      'enterprise-cloud@latest',
    )
  })

  test('reads an explicit enterprise-server release prefix', () => {
    expect(versionFromResolvedKey('/en/enterprise-server@3.17/actions/foo')).toBe(
      'enterprise-server@3.17',
    )
  })

  test('reads a free-pro-team prefix when present', () => {
    expect(versionFromResolvedKey('/en/free-pro-team@latest/actions/foo')).toBe(
      'free-pro-team@latest',
    )
  })

  test('returns null for an unknown version token', () => {
    expect(versionFromResolvedKey('/en/enterprise-server@9.99/actions/foo')).toBe(null)
  })

  test('handles keys without a language prefix', () => {
    expect(versionFromResolvedKey('/enterprise-cloud@latest/actions/foo')).toBe(
      'enterprise-cloud@latest',
    )
  })
})

describe('isAnchorCheckableTarget', () => {
  const asPage = (partial: Record<string, unknown>): Page => partial as unknown as Page

  test('checkable for an ordinary Markdown page', () => {
    expect(isAnchorCheckableTarget(asPage({ markdown: '## A heading\n\ntext' }))).toBe(true)
  })

  test('not checkable for an autogenerated page', () => {
    expect(isAnchorCheckableTarget(asPage({ autogenerated: true, markdown: '' }))).toBe(false)
  })

  test('not checkable for the glossary loop page', () => {
    const markdown =
      'intro\n\n{% for glossary in glossaries %}\n\n## {{ glossary.term }}\n{% endfor %}'
    expect(isAnchorCheckableTarget(asPage({ markdown }))).toBe(false)
  })

  test('tolerates whitespace variations in the glossary loop tag', () => {
    const markdown = '{%- for term in glossaries -%}\n## {{ term.term }}\n{%- endfor -%}'
    expect(isAnchorCheckableTarget(asPage({ markdown }))).toBe(false)
  })
})

describe('findLinkLines', () => {
  test('finds the line a link occurs on', () => {
    const content = ['# Title', '', 'See [docs](/actions/foo#bar) for more.'].join('\n')
    expect(findLinkLines(content, '/actions/foo#bar')).toEqual([3])
  })

  test('does not match a fragment that merely starts with the needle', () => {
    // A substring search would report line 1 for `/a#foo` because `/a#foobar` starts with it.
    const content = ['[x](/a#foobar)', '[y](/a#foo)'].join('\n')
    expect(findLinkLines(content, '/a#foo')).toEqual([2])
  })

  test('does not match a path that merely starts with the needle', () => {
    const content = ['[x](/actions/foobar#bar)', '[y](/actions/foo#bar)'].join('\n')
    expect(findLinkLines(content, '/actions/foo#bar')).toEqual([2])
  })

  test('matches a destination followed by a title', () => {
    expect(findLinkLines('[x](/a#foo "A title")', '/a#foo')).toEqual([1])
  })

  test('matches a destination at end of line', () => {
    expect(findLinkLines('[x](/a#foo', '/a#foo')).toEqual([1])
  })

  test('reports each line once even with repeats', () => {
    const content = '[x](/a#foo) and again [y](/a#foo)'
    expect(findLinkLines(content, '/a#foo')).toEqual([1])
  })

  test('finds a real link on a line that also holds a longer near-match', () => {
    expect(findLinkLines('[x](/a#foobar) [y](/a#foo)', '/a#foo')).toEqual([1])
  })

  test('returns empty when absent', () => {
    expect(findLinkLines('no links here', '/a#foo')).toEqual([])
  })
})

describe('resolveLinkKeyForVersion', () => {
  // A GHEC-only target has no unversioned permalink, so a bare href only resolves when
  // retried against the source page's version.
  const pageMap = {
    '/en/get-started/foo': {} as Page,
    '/en/enterprise-cloud@latest/admin/bar': {} as Page,
    '/en/enterprise-server@3.17/admin/baz': {} as Page,
  }

  test('resolves an href that already matches a key', () => {
    expect(resolveLinkKeyForVersion('/get-started/foo', 'free-pro-team@latest', pageMap)).toBe(
      '/en/get-started/foo',
    )
  })

  test('resolves an unversioned href against the source version', () => {
    expect(resolveLinkKeyForVersion('/admin/bar', 'enterprise-cloud@latest', pageMap)).toBe(
      '/en/enterprise-cloud@latest/admin/bar',
    )
    expect(resolveLinkKeyForVersion('/admin/baz', 'enterprise-server@3.17', pageMap)).toBe(
      '/en/enterprise-server@3.17/admin/baz',
    )
  })

  test('strips an existing language prefix before retrying', () => {
    expect(resolveLinkKeyForVersion('/en/admin/bar', 'enterprise-cloud@latest', pageMap)).toBe(
      '/en/enterprise-cloud@latest/admin/bar',
    )
  })

  test('does not retry an href that carries its own version', () => {
    expect(
      resolveLinkKeyForVersion(
        '/enterprise-server@3.17/admin/bar',
        'enterprise-cloud@latest',
        pageMap,
      ),
    ).toBe(null)
  })

  test('returns null when the target does not exist in that version', () => {
    expect(resolveLinkKeyForVersion('/admin/bar', 'enterprise-server@3.17', pageMap)).toBe(null)
    expect(resolveLinkKeyForVersion('/nope/nope', 'free-pro-team@latest', pageMap)).toBe(null)
  })

  test('ignores a fragment and query string', () => {
    expect(
      resolveLinkKeyForVersion('/admin/bar?x=1#some-heading', 'enterprise-cloud@latest', pageMap),
    ).toBe('/en/enterprise-cloud@latest/admin/bar')
  })
})
