import { describe, expect, test, vi } from 'vitest'

import { RedirectedFragmentValidator } from '../lib/validate-redirected-fragment'
import { renderMarkdownLiquid } from '@/links/lib/extract-links'
import type { Page } from '@/types'

// Stub rendering and warming so render-failure tests avoid loading the site.
vi.mock('@/links/lib/extract-links', () => ({
  renderMarkdownLiquid: vi.fn(),
}))
vi.mock('@/frame/lib/warm-server', () => ({
  default: vi.fn(async () => ({})),
}))

// Fixed heading IDs isolate keep, drop, mixed, and unvalidatable decisions from rendering.
class StubValidator extends RedirectedFragmentValidator {
  constructor(private idsByKey: Record<string, Set<string> | null>) {
    super({}, {}, 'en')
  }
  protected async headingIdsFor(page: Page, version: string): Promise<Set<string> | null> {
    const key = `${version}|${page.relativePath}`
    return key in this.idsByKey ? this.idsByKey[key] : new Set<string>()
  }
}

function fakePage(overrides: Partial<Page>): Page {
  return {
    relativePath: 'content/foo.md',
    applicableVersions: ['free-pro-team@latest'],
    markdown: '',
    ...overrides,
  } as unknown as Page
}

describe('RedirectedFragmentValidator.classify', () => {
  test('keep: anchor exists in every applicable version', async () => {
    const page = fakePage({
      applicableVersions: ['free-pro-team@latest', 'enterprise-cloud@latest'],
    })
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['intro', 'setup']),
      'enterprise-cloud@latest|content/foo.md': new Set(['intro', 'setup']),
    })
    expect(await validator.classify(page, '#setup')).toBe('keep')
  })

  test('drop: anchor is absent from every applicable version', async () => {
    const page = fakePage({
      applicableVersions: ['free-pro-team@latest', 'enterprise-cloud@latest'],
    })
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['intro']),
      'enterprise-cloud@latest|content/foo.md': new Set(['intro']),
    })
    expect(await validator.classify(page, '#setup')).toBe('drop')
  })

  test('mixed: anchor exists in some but not all versions', async () => {
    const page = fakePage({
      applicableVersions: ['free-pro-team@latest', 'enterprise-cloud@latest'],
    })
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['intro', 'setup']),
      'enterprise-cloud@latest|content/foo.md': new Set(['intro']),
    })
    expect(await validator.classify(page, '#setup')).toBe('mixed')
  })

  test('unvalidatable: no destination page', async () => {
    const validator = new StubValidator({})
    expect(await validator.classify(undefined, '#setup')).toBe('unvalidatable')
  })

  test('unvalidatable: autogenerated destination page', async () => {
    const page = fakePage({ autogenerated: 'rest' })
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['intro']),
    })
    expect(await validator.classify(page, '#setup')).toBe('unvalidatable')
  })

  test('unvalidatable: destination has no applicable versions', async () => {
    const page = fakePage({ applicableVersions: [] })
    const validator = new StubValidator({})
    expect(await validator.classify(page, '#setup')).toBe('unvalidatable')
  })

  test('unvalidatable: a version fails to render (never risk a destructive drop)', async () => {
    const page = fakePage({
      applicableVersions: ['free-pro-team@latest', 'enterprise-cloud@latest'],
    })
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['intro']),
      // null models a render failure, which must not lead to a drop.
      'enterprise-cloud@latest|content/foo.md': null,
    })
    expect(await validator.classify(page, '#setup')).toBe('unvalidatable')
  })

  test('keep: empty fragment is a no-op', async () => {
    const page = fakePage({})
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(),
    })
    expect(await validator.classify(page, '#')).toBe('keep')
  })

  test('keep: #top is always valid', async () => {
    // Browsers scroll to the top for #top, so computed heading IDs never include it.
    const page = fakePage({})
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['intro']),
    })
    expect(await validator.classify(page, '#top')).toBe('keep')
  })

  test('handles a fragment passed without the leading hash', async () => {
    const page = fakePage({})
    const validator = new StubValidator({
      'free-pro-team@latest|content/foo.md': new Set(['setup']),
    })
    expect(await validator.classify(page, 'setup')).toBe('keep')
  })
})

describe('RedirectedFragmentValidator.headingIdsFor render failures', () => {
  test('unvalidatable, not drop, when the destination fails to render', async () => {
    // headingIdsFor must use renderMarkdownLiquid, not renderAndExtractLinks, to avoid false drops.
    vi.mocked(renderMarkdownLiquid).mockRejectedValueOnce(new Error('Liquid syntax error'))

    const page = fakePage({
      relativePath: 'content/bar.md',
      applicableVersions: ['free-pro-team@latest'],
      markdown: '## {% data variables.product.prodname_dotcom %} settings\n',
    })
    const validator = new RedirectedFragmentValidator({}, {}, 'en')

    expect(await validator.classify(page, '#github-settings')).toBe('unvalidatable')
  })

  test('drop still works when the destination renders cleanly', async () => {
    vi.mocked(renderMarkdownLiquid).mockResolvedValueOnce('## Intro\n')

    const page = fakePage({
      relativePath: 'content/baz.md',
      applicableVersions: ['free-pro-team@latest'],
      markdown: '## Intro\n',
    })
    const validator = new RedirectedFragmentValidator({}, {}, 'en')

    expect(await validator.classify(page, '#setup')).toBe('drop')
  })
})
