#!/usr/bin/env bash

# @purpose Writer tool
# @description Clone the docs-early-access repo

set -e

pushd .. > /dev/null

if [ -d "docs-early-access" ]; then
  echo "A 'docs-early-access' directory already exists!"
  popd > /dev/null
  exit 0
fi

git clone https://github.com/github/docs-early-access.git

popd > /dev/null

npm run symlink-from-local-repo -- -p ../docs-early-access

echo -e '\nDone!'
