import { describe, expect, test, vi } from 'vitest'
import type { NextFunction, Response } from 'express'

import genericToc from '@/frame/middleware/context/generic-toc'
import type { ExtendedRequest, Page, Tree } from '@/types'

type TestPage = Pick<Page, 'documentType' | 'relativePath' | 'renderProp'> &
  Partial<Pick<Page, 'autogenerated' | 'earlyAccessToc' | 'hidden'>>

function createPage(overrides: Partial<TestPage>): Page {
  return {
    documentType: 'article',
    relativePath: 'product/category/article.md',
    hidden: false,
    async renderProp(prop: string) {
      return prop === 'rawIntro' ? 'Intro' : 'Title'
    },
    ...overrides,
  } as Page
}

function createTree(page: Page, children: Tree[] = []): Tree {
  return {
    page,
    children: children.map((child) => child.page.relativePath),
    href: `/en/${page.relativePath.replace(/\/index\.md$|\.md$/, '')}`,
    childPages: children,
  }
}

function createRequest(treePage: Tree, page: Page): ExtendedRequest {
  return {
    pagePath: treePage.href,
    context: {
      page,
      currentLayoutName: 'default',
      currentProductTree: treePage,
      currentEnglishTree: treePage,
      currentPath: treePage.href,
    },
  } as ExtendedRequest
}

describe('genericToc middleware', () => {
  const response = {} as Response

  test('uses a flat TOC for categories whose child pages have no children', async () => {
    const category = createPage({
      documentType: 'category',
      relativePath: 'product/category/index.md',
    })
    const child = createPage({ relativePath: 'product/category/article.md' })
    const treePage = createTree(category, [createTree(child)])
    const req = createRequest(treePage, category)
    const next = vi.fn() as NextFunction

    await genericToc(req, response, next)

    expect(req.context?.genericTocFlat).toEqual([
      expect.objectContaining({
        fullPath: '/en/product/category/article',
        title: 'Title',
        childTocItems: [],
      }),
    ])
    expect(req.context?.genericTocNested).toBeUndefined()
    expect(next).toHaveBeenCalledOnce()
  })

  test('uses a nested TOC for categories whose child pages have children', async () => {
    const category = createPage({
      documentType: 'category',
      relativePath: 'product/category/index.md',
    })
    const child = createPage({
      documentType: 'subcategory',
      relativePath: 'product/category/subcategory/index.md',
    })
    const grandchild = createPage({
      relativePath: 'product/category/subcategory/article.md',
    })
    const treePage = createTree(category, [createTree(child, [createTree(grandchild)])])
    const req = createRequest(treePage, category)
    const next = vi.fn() as NextFunction

    await genericToc(req, response, next)

    expect(req.context?.genericTocFlat).toBeUndefined()
    expect(req.context?.genericTocNested).toEqual([
      expect.objectContaining({
        fullPath: '/en/product/category/subcategory',
        title: 'Title',
        intro: null,
        childTocItems: [
          expect.objectContaining({
            fullPath: '/en/product/category/subcategory/article',
            title: 'Title',
          }),
        ],
      }),
    ])
    expect(next).toHaveBeenCalledOnce()
  })

  test('uses a flat TOC when child pages declare children but none apply to this version', async () => {
    const category = createPage({
      documentType: 'category',
      relativePath: 'product/category/index.md',
    })
    const child = createPage({
      documentType: 'subcategory',
      relativePath: 'product/category/subcategory/index.md',
    })
    const childTree = { ...createTree(child), children: ['/other-version-only'] }
    const treePage = createTree(category, [childTree])
    const req = createRequest(treePage, category)
    const next = vi.fn() as NextFunction

    await genericToc(req, response, next)

    expect(req.context?.genericTocFlat).toHaveLength(1)
    expect(req.context?.genericTocNested).toBeUndefined()
  })
})
