import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import type { CategorizedEvents } from '@/audit-logs/types'
import type { TitleResolutionContext } from '@/audit-logs/lib/index'
import { renderContent } from '@/content-render/index'
import { loadTemplate } from '@/article-api/lib/load-template'
import matter from '@gr2m/gray-matter'

export class AuditLogsTransformer implements PageTransformer {
  templateName = 'audit-logs-page.template.md'

  canTransform(page: Page): boolean {
    return page.autogenerated === 'audit-logs'
  }

  async transform(page: Page, pathname: string, context: Context): Promise<string> {
    // Dynamic import avoids circular dependencies.
    const { getCategorizedAuditLogEvents, getCategoryNotes, resolveReferenceLinksToMarkdown } =
      await import('@/audit-logs/lib/index')

    const currentVersion = context.currentVersion!

    let pageType = ''
    if (pathname.includes('/security-log-events')) {
      pageType = 'user'
    } else if (pathname.includes('/audit-log-events-for-your-enterprise')) {
      pageType = 'enterprise'
    } else if (pathname.includes('/audit-log-events-for-your-organization')) {
      pageType = 'organization'
    } else {
      throw new Error(`Unknown audit log page type for path: ${pathname}`)
    }

    const categorizedEvents = getCategorizedAuditLogEvents(pageType, currentVersion)
    const categoryNotes = getCategoryNotes()

    let manualContent = ''
    if (page.markdown) {
      const markerIndex = page.markdown.indexOf(
        '<!-- Content after this section is automatically generated -->',
      )
      if (markerIndex > 0) {
        const { content } = matter(page.markdown)
        const manualContentMarkerIndex = content.indexOf(
          '<!-- Content after this section is automatically generated -->',
        )
        if (manualContentMarkerIndex > 0) {
          const rawManualContent = content.substring(0, manualContentMarkerIndex).trim()
          if (rawManualContent) {
            manualContent = await renderContent(rawManualContent, {
              ...context,
              markdownRequested: true,
            })
          }
        }
      }
    }

    const templateData = await this.prepareTemplateData(
      page,
      categorizedEvents,
      categoryNotes,
      context,
      manualContent,
      resolveReferenceLinksToMarkdown,
    )

    const templateContent = loadTemplate(this.templateName)

    const rendered = await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })

    return rendered
  }

  private async prepareTemplateData(
    page: Page,
    categorizedEvents: CategorizedEvents,
    categoryNotes: Record<string, string>,
    context: Context,
    manualContent: string,
    resolveReferenceLinksToMarkdown: (
      docsReferenceLinks: string,
      context: TitleResolutionContext,
    ) => Promise<string>,
  ): Promise<Record<string, unknown>> {
    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    const allFieldSets: string[][] = []
    const sortedCategorizedEvents: CategorizedEvents = {}
    const sortedCategories = Object.keys(categorizedEvents).sort((a, b) => a.localeCompare(b))

    for (const category of sortedCategories) {
      // Copy cached array before sorting; clone events before resolving links or trimming fields.
      const events = [...categorizedEvents[category]].sort((a, b) =>
        a.action.localeCompare(b.action),
      )
      sortedCategorizedEvents[category] = await Promise.all(
        events.map(async (event) => {
          const newEvent = { ...event }
          if (newEvent.docs_reference_links && newEvent.docs_reference_links !== 'N/A') {
            newEvent.docs_reference_links = await resolveReferenceLinksToMarkdown(
              newEvent.docs_reference_links,
              context as TitleResolutionContext,
            )
          }
          if (newEvent.fields) {
            allFieldSets.push(newEvent.fields)
          }
          return newEvent
        }),
      )
    }

    // Base fields appear in at least 80 percent of events.
    const fieldCounts = new Map<string, number>()
    for (const fields of allFieldSets) {
      for (const f of fields) {
        fieldCounts.set(f, (fieldCounts.get(f) || 0) + 1)
      }
    }
    const threshold = allFieldSets.length * 0.8
    const baseFields = [...fieldCounts.entries()]
      .filter(([, count]) => count >= threshold)
      .map(([field]) => field)
      .sort()

    // Event rows omit base fields because the template lists them once.
    const baseFieldSet = new Set(baseFields)
    for (const category of Object.keys(sortedCategorizedEvents)) {
      for (const event of sortedCategorizedEvents[category]) {
        if (event.fields) {
          event.fields = event.fields.filter((f: string) => !baseFieldSet.has(f))
        }
      }
    }

    return {
      page: {
        title: page.title,
        intro,
      },
      manualContent,
      categorizedEvents: sortedCategorizedEvents,
      categoryNotes,
      baseFields,
    }
  }
}
