import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { renderContent } from '@/content-render/index'
import { loadTemplate } from '@/article-api/lib/load-template'
import { stripHtmlCommentsAndNormalizeWhitespace } from '@/article-api/lib/strip-html-comments'

export class CodeQLCliTransformer implements PageTransformer {
  templateName = 'codeql-cli-page.template.md'

  canTransform(page: Page): boolean {
    return page.autogenerated === 'codeql-cli'
  }

  async transform(page: Page, _pathname: string, context: Context): Promise<string> {
    // Fully generated CodeQL CLI pages need markdownRequested=true to render markdown output.
    context.markdownRequested = true
    const content = await page.render(context)

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    const templateData: Record<string, unknown> = {
      page: {
        title: page.title,
        intro,
      },
      content,
    }

    const templateContent = loadTemplate(this.templateName)

    const result = await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })

    // Strip markdownlint-disable and any other HTML comments.
    return stripHtmlCommentsAndNormalizeWhitespace(result)
  }
}
