import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { renderContent } from '@/content-render/index'
import { loadTemplate } from '@/article-api/lib/load-template'
import { stripHtmlCommentsAndNormalizeWhitespace } from '@/article-api/lib/strip-html-comments'

/**
 * Transformer for CodeQL CLI reference pages.
 * Renders autogenerated CodeQL CLI documentation pages as markdown using a Liquid template.
 * Sets `markdownRequested` to true in the context to ensure the page is rendered as markdown,
 * bypassing the default article type check.
 */
export class CodeQLCliTransformer implements PageTransformer {
  templateName = 'codeql-cli-page.template.md'

  canTransform(page: Page): boolean {
    return page.autogenerated === 'codeql-cli'
  }

  async transform(page: Page, _pathname: string, context: Context): Promise<string> {
    // CodeQL CLI pages are fully generated markdown files in the repo.
    // We render them with markdownRequested=true to get the markdown output.
    context.markdownRequested = true
    const content = await page.render(context)

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    // Prepare template data
    const templateData: Record<string, unknown> = {
      page: {
        title: page.title,
        intro,
      },
      content,
    }

    // Load and render template
    const templateContent = loadTemplate(this.templateName)

    const result = await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })

    // Strip HTML comments (e.g., markdownlint-disable comments) from the output
    return stripHtmlCommentsAndNormalizeWhitespace(result)
  }
}
