import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { stripHtmlCommentsAndNormalizeWhitespace } from '@/article-api/lib/strip-html-comments'

/**
 * Transformer for CodeQL CLI reference pages.
 * Renders autogenerated CodeQL CLI documentation pages as markdown.
 * Sets `markdownRequested` to true in the context to ensure the page is rendered as markdown,
 * bypassing the default article type check.
 */
export class CodeQLCliTransformer implements PageTransformer {
  canTransform(page: Page): boolean {
    return page.autogenerated === 'codeql-cli'
  }

  async transform(page: Page, _pathname: string, context: Context): Promise<string> {
    // CodeQL CLI pages are fully generated markdown files in the repo.
    // We render them with markdownRequested=true to get the markdown output,
    // similar to how regular articles are rendered but through the transformer pattern.
    context.markdownRequested = true
    const content = await page.render(context)

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    const result = `# ${page.title}\n\n${intro}\n\n${content}`

    // Strip HTML comments (e.g., markdownlint-disable comments) from the output
    return stripHtmlCommentsAndNormalizeWhitespace(result)
  }
}
