import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import type {
  QueryT,
  MutationT,
  ObjectT,
  InterfaceT,
  EnumT,
  UnionT,
  InputObjectT,
  ScalarT,
  FieldT,
} from '@/graphql/components/types'
import { renderContent } from '@/content-render/index'
import { loadTemplate } from '@/article-api/lib/load-template'
import { fastTextOnly } from '@/content-render/unified/text-only'
import { extractManualContent } from '@/article-api/lib/graphql-helpers'

/**
 * Transformer for GraphQL reference pages (queries, mutations, objects, etc.)
 * Renders schema items with their fields and arguments
 */
export class GraphQLReferenceTransformer implements PageTransformer {
  templateName = 'graphql-reference.template.md'

  canTransform(page: Page): boolean {
    if (page.autogenerated !== 'graphql') return false

    // Match reference pages that have a specific page type (not index)
    const isReference = page.relativePath.includes('graphql/reference/')
    const isNotIndex = !page.relativePath.endsWith('index.md')

    return isReference && isNotIndex
  }

  async transform(page: Page, pathname: string, context: Context): Promise<string> {
    const currentVersion = context.currentVersion!

    // Determine the page slug from the pathname
    const pathParts = pathname.split('/').filter(Boolean)
    const graphqlIndex = pathParts.indexOf('graphql')
    const pageType = pathParts[graphqlIndex + 2] // category slug like 'repos', 'issues', etc.

    const { getGraphqlSchema, getAllGraphqlObjects } = await import('@/graphql/lib/index')
    const { isValidCategory, ALL_KIND_KEYS, KIND_SLUG_PREFIX } =
      await import('@/graphql/lib/categories')

    // Category pages render every kind in a fixed section order. The mini-toc
    // and in-page anchors use kind-disambiguated slugs so items sharing a
    // case-insensitive name across kinds (e.g. `Repository` object vs
    // `repository` query) don't collide.
    if (!isValidCategory(pageType)) {
      // Defensive: legacy kind URLs redirect to /graphql/reference, so this
      // transformer should never see them. Returning empty content lets the
      // 404 path handle anything unexpected.
      return ''
    }

    const schema = getGraphqlSchema(currentVersion, pageType)
    const allObjects = getAllGraphqlObjects(currentVersion)

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''
    const manualContent = await extractManualContent(page, context)

    // Flatten every kind into a single alphabetical list. Each prepared item
    // carries its kind label so the template can render a "name - kind"
    // disambiguator next to the heading without grouping by kind sections.
    const KIND_DISPLAY: Record<string, string> = {
      queries: 'query',
      mutations: 'mutation',
      objects: 'object',
      interfaces: 'interface',
      enums: 'enum',
      unions: 'union',
      inputObjects: 'input object',
      scalars: 'scalar',
    }

    const flatEntries: Array<{ kind: string; item: Record<string, unknown> }> = []
    for (const kind of ALL_KIND_KEYS) {
      const items = (schema as Record<string, unknown[]>)[kind] as
        | Array<{ name: string; [k: string]: unknown }>
        | undefined
      if (!items || items.length === 0) continue
      const preparedKindItems = await Promise.all(
        items.map(async (item) => {
          const prepared = await this.prepareByKind(kind, item, allObjects, KIND_SLUG_PREFIX[kind])
          prepared.kind = kind
          prepared.kindLabel = KIND_DISPLAY[kind] ?? kind
          return prepared
        }),
      )
      for (const prepared of preparedKindItems) {
        flatEntries.push({ kind, item: prepared })
      }
    }
    flatEntries.sort((a, b) => {
      const an = String(a.item.name ?? '').toLowerCase()
      const bn = String(b.item.name ?? '').toLowerCase()
      if (an < bn) return -1
      if (an > bn) return 1
      return a.kind < b.kind ? -1 : a.kind > b.kind ? 1 : 0
    })
    const items = flatEntries.map((e) => e.item)

    const templateData: Record<string, unknown> = {
      pageTitle: page.title,
      pageIntro: intro,
      manualContent,
      items,
    }

    const templateContent = loadTemplate(this.templateName)

    return await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })
  }

  // Dispatch an item to the appropriate prepare* helper based on kind. The
  // resulting slug is kind-disambiguated to match the in-page anchors.
  private async prepareByKind(
    kind: string,
    item: { name: string; [k: string]: unknown },
    allObjects: Array<{ name: string; implements?: Array<{ name: string }>; href?: string }>,
    slugPrefix: string,
  ): Promise<Record<string, unknown>> {
    let prepared: Record<string, unknown>
    switch (kind) {
      case 'queries':
        prepared = await this.prepareQuery(item as never)
        break
      case 'mutations':
        prepared = await this.prepareMutation(item as never)
        break
      case 'objects':
        prepared = await this.prepareObject(item as never)
        break
      case 'interfaces': {
        const base = (await this.prepareInterface(item as never)) as Record<string, unknown> & {
          implementedBy?: unknown
        }
        const implementers = allObjects.filter(
          (obj) => obj.implements && obj.implements.some((i) => i.name === item.name),
        )
        base.implementedBy = implementers.map((obj) => ({ name: obj.name, href: obj.href }))
        prepared = base
        break
      }
      case 'enums':
        prepared = await this.prepareEnum(item as never)
        break
      case 'unions':
        prepared = await this.prepareUnion(item as never)
        break
      case 'inputObjects':
        prepared = await this.prepareInputObject(item as never)
        break
      case 'scalars':
        prepared = await this.prepareScalar(item as never)
        break
      default:
        prepared = {}
    }
    // Override `slug` with the kind-disambiguated form used by the React page.
    prepared.slug = `${slugPrefix}-${(prepared.slug as string | undefined) ?? item.name.toLowerCase()}`
    return prepared
  }

  /**
   * Prepare a query item for rendering
   */
  private async prepareQuery(query: QueryT): Promise<Record<string, unknown>> {
    return {
      name: query.name,
      slug: query.name.toLowerCase(),
      description: query.description ? fastTextOnly(query.description) : '',
      type: query.type,
      href: query.href,
      isDeprecated: query.isDeprecated || false,
      deprecationReason: query.deprecationReason
        ? fastTextOnly(query.deprecationReason)
        : undefined,
      args: query.args.map((arg) => ({
        name: arg.name,
        type: arg.type,
        href: arg.href,
        description: arg.description ? fastTextOnly(arg.description) : '',
      })),
    }
  }

  /**
   * Prepare a mutation item for rendering
   */
  private async prepareMutation(mutation: MutationT): Promise<Record<string, unknown>> {
    return {
      name: mutation.name,
      slug: mutation.name.toLowerCase(),
      description: mutation.description ? fastTextOnly(mutation.description) : '',
      isDeprecated: mutation.isDeprecated || false,
      deprecationReason: mutation.deprecationReason
        ? fastTextOnly(mutation.deprecationReason)
        : undefined,
      inputFields: await this.prepareFields(mutation.inputFields),
      returnFields: await this.prepareFields(mutation.returnFields),
    }
  }

  /**
   * Prepare an object item for rendering
   */
  private async prepareObject(object: ObjectT): Promise<Record<string, unknown>> {
    return {
      name: object.name,
      slug: object.name.toLowerCase(),
      description: object.description ? fastTextOnly(object.description) : '',
      isDeprecated: object.isDeprecated || false,
      deprecationReason: object.deprecationReason
        ? fastTextOnly(object.deprecationReason)
        : undefined,
      implements: object.implements || [],
      fields: await this.prepareFields(object.fields),
    }
  }

  /**
   * Prepare an interface item for rendering
   */
  private async prepareInterface(item: InterfaceT): Promise<Record<string, unknown>> {
    return {
      name: item.name,
      slug: item.name.toLowerCase(),
      description: item.description ? fastTextOnly(item.description) : '',
      isDeprecated: item.isDeprecated || false,
      deprecationReason: item.deprecationReason ? fastTextOnly(item.deprecationReason) : undefined,
      fields: await this.prepareFields(item.fields),
    }
  }

  /**
   * Prepare an enum item for rendering
   */
  private async prepareEnum(item: EnumT): Promise<Record<string, unknown>> {
    return {
      name: item.name,
      slug: item.name.toLowerCase(),
      description: item.description ? fastTextOnly(item.description) : '',
      isDeprecated: item.isDeprecated || false,
      deprecationReason: item.deprecationReason ? fastTextOnly(item.deprecationReason) : undefined,
      values: item.values.map((value) => ({
        name: value.name,
        description: value.description ? fastTextOnly(value.description) : '',
      })),
    }
  }

  /**
   * Prepare a union item for rendering
   */
  private async prepareUnion(item: UnionT): Promise<Record<string, unknown>> {
    return {
      name: item.name,
      slug: item.name.toLowerCase(),
      description: item.description ? fastTextOnly(item.description) : '',
      isDeprecated: item.isDeprecated || false,
      deprecationReason: item.deprecationReason ? fastTextOnly(item.deprecationReason) : undefined,
      possibleTypes: item.possibleTypes || [],
    }
  }

  /**
   * Prepare an input object item for rendering
   */
  private async prepareInputObject(item: InputObjectT): Promise<Record<string, unknown>> {
    return {
      name: item.name,
      slug: item.name.toLowerCase(),
      description: item.description ? fastTextOnly(item.description) : '',
      isDeprecated: item.isDeprecated || false,
      deprecationReason: item.deprecationReason ? fastTextOnly(item.deprecationReason) : undefined,
      inputFields: await this.prepareFields(item.inputFields),
    }
  }

  /**
   * Prepare a scalar item for rendering
   */
  private async prepareScalar(item: ScalarT): Promise<Record<string, unknown>> {
    return {
      name: item.name,
      slug: item.name.toLowerCase(),
      description: item.description ? fastTextOnly(item.description) : '',
      isDeprecated: item.isDeprecated || false,
      deprecationReason: item.deprecationReason ? fastTextOnly(item.deprecationReason) : undefined,
    }
  }

  private static STANDARD_PAGINATION_ARGS = new Set(['after', 'before', 'first', 'last'])

  /**
   * Check if a field has only the standard pagination arguments
   * (after, before, first, last) with no additional args.
   */
  private hasOnlyStandardPaginationArgs(field: FieldT): boolean {
    if (!field.arguments || field.arguments.length !== 4) return false
    return field.arguments.every((arg) =>
      GraphQLReferenceTransformer.STANDARD_PAGINATION_ARGS.has(arg.name),
    )
  }

  /**
   * Prepare fields for rendering
   */
  private async prepareFields(fields: FieldT[]): Promise<Array<Record<string, unknown>>> {
    return fields.map((field) => {
      const hasPaginationOnly = this.hasOnlyStandardPaginationArgs(field)
      return {
        name: field.name,
        type: field.type,
        href: field.href,
        description: field.description ? fastTextOnly(field.description) : '',
        defaultValue: field.defaultValue,
        isDeprecated: field.isDeprecated || false,
        deprecationReason: field.deprecationReason
          ? fastTextOnly(field.deprecationReason)
          : undefined,
        hasPaginationOnly,
        arguments:
          field.arguments && !hasPaginationOnly
            ? field.arguments.map((arg) => ({
                name: arg.name,
                description: arg.description ? fastTextOnly(arg.description) : '',
                defaultValue: arg.defaultValue,
                type: {
                  name: arg.type.name,
                  href: arg.type.href,
                },
              }))
            : undefined,
      }
    })
  }
}
