import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { renderContent } from '@/content-render/index'
import { loadTemplate } from '@/article-api/lib/load-template'
import { extractManualContent } from '@/article-api/lib/graphql-helpers'

/**
 * Transformer for GraphQL reference index page
 * Renders the index page with links to child pages
 */
export class GraphQLIndexTransformer implements PageTransformer {
  templateName = 'graphql-index.template.md'

  canTransform(page: Page): boolean {
    if (page.autogenerated !== 'graphql') return false

    // Match the reference index page (no specific page type after /reference)
    return page.relativePath.endsWith('graphql/reference/index.md')
  }

  async transform(page: Page, _pathname: string, context: Context): Promise<string> {
    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    const manualContent = await extractManualContent(page, context)

    // Get children links from page metadata
    const children = page.children || []
    const childrenLinks = children
      .map((child) => {
        const childPath = child.startsWith('/') ? child : `/${child}`
        const childName = childPath.split('/').pop() || ''
        const displayName = childName
          .split('-')
          .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
          .join(' ')
        return `- [${displayName}](${childPath})`
      })
      .join('\n')

    const templateData: Record<string, unknown> = {
      pageTitle: page.title,
      pageIntro: intro,
      manualContent,
      childrenLinks,
    }

    const templateContent = loadTemplate(this.templateName)

    return await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })
  }
}
