import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import type { BreakingChangesT } from '@/graphql/components/types'
import { renderContent } from '@/content-render/index'
import { loadTemplate } from '@/article-api/lib/load-template'
import { fastTextOnly } from '@/content-render/unified/text-only'
import { extractManualContent } from '@/article-api/lib/graphql-helpers'
import GithubSlugger from 'github-slugger'

/**
 * Transformer for GraphQL breaking changes page
 * Renders breaking changes organized by date
 */
export class GraphQLBreakingChangesTransformer implements PageTransformer {
  templateName = 'graphql-breaking-changes.template.md'

  canTransform(page: Page): boolean {
    if (page.autogenerated !== 'graphql') return false

    return page.relativePath.includes('graphql/overview/breaking-changes')
  }

  async transform(page: Page, _pathname: string, context: Context): Promise<string> {
    const currentVersion = context.currentVersion!

    const { getGraphqlBreakingChanges } = await import('@/graphql/lib/index')

    const schema = getGraphqlBreakingChanges(currentVersion) as BreakingChangesT

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''
    const manualContent = await extractManualContent(page, context)

    const slugger = new GithubSlugger()

    // Process breaking changes by date
    const breakingChangesByDate = Object.keys(schema).map((date) => {
      const items = schema[date]
      const heading = `Changes scheduled for ${date}`
      const slug = slugger.slug(heading)

      return {
        date,
        heading,
        slug,
        items: items.map((item) => ({
          location: item.location,
          description: fastTextOnly(item.description),
          reason: fastTextOnly(item.reason),
          criticality: item.criticality,
        })),
      }
    })

    const templateData: Record<string, unknown> = {
      pageTitle: page.title,
      pageIntro: intro,
      manualContent,
      breakingChangesByDate,
    }

    const templateContent = loadTemplate(this.templateName)

    return await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })
  }
}
