import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import type { Operation } from '@/rest/components/types'
import { renderContent } from '@/content-render/index'
import { engine } from '@/content-render/liquid/engine'
import { apiTransformerTags } from '@/article-api/liquid-renderers'
import { loadTemplate } from '@/article-api/lib/load-template'
import { summarizeSchema } from '@/article-api/lib/summarize-schema'
import {
  getCurlBodyArguments,
  needsExplicitContentTypeHeader,
} from '@/rest/lib/curl-body-arguments'
import matter from '@gr2m/gray-matter'
import { fastTextOnly } from '@/content-render/unified/text-only'
import GithubSlugger from 'github-slugger'

// REST templates need these article-api-specific Liquid tags.
// Register them here, not in engine.ts, to avoid a cycle from rest-tags to renderContent to engine.
for (const [tagName, tagClass] of Object.entries(apiTransformerTags)) {
  engine.registerTag(tagName, tagClass as unknown as Parameters<typeof engine.registerTag>[1])
}

const DEBUG = process.env.RUNNER_DEBUG === '1' || process.env.DEBUG === '1'

type PreparedCodeExample = {
  request: {
    description: string
    url: string
    acceptHeader?: string
    contentType?: string
    needsContentTypeHeader: boolean
    bodyParameters: string[]
  }
  response: {
    statusCode?: string
    schema: string | null
  }
}

type PreparedOperation = Omit<Operation, 'statusCodes' | 'codeExamples'> & {
  description: string
  hasParameters: boolean
  showHeaders: boolean
  needsContentTypeHeader: boolean
  statusCodes?: Array<{ httpStatusCode: string; description?: string }>
  codeExamples: PreparedCodeExample[]
}

type PreparedTemplateData = {
  page: {
    title: Page['title']
    intro: string
  }
  manualContent: string
  restOperations: PreparedOperation[]
  apiVersion?: string
}

export class RestTransformer implements PageTransformer {
  templateName = 'rest-page.template.md'

  canTransform(page: Page): boolean {
    // A different transformer handles landing pages like /en/rest.
    return page.autogenerated === 'rest' && !page.relativePath.endsWith('index.md')
  }

  async transform(
    page: Page,
    pathname: string,
    context: Context,
    apiVersion?: string,
  ): Promise<string> {
    const startTime = DEBUG ? Date.now() : 0
    if (DEBUG) console.log(`[DEBUG] RestTransformer: ${pathname}`)

    // Dynamic import avoids circular dependencies.
    const { default: getRest } = await import('@/rest/lib/index')

    const currentVersion = context.currentVersion!

    const effectiveApiVersion =
      apiVersion ||
      (context.currentVersionObj?.apiVersions?.length
        ? context.currentVersionObj.latestApiVersion
        : undefined)

    // /en/rest/actions/artifacts resolves to category actions and subcategory artifacts.
    const pathParts = pathname.split('/').filter(Boolean)
    const restIndex = pathParts.indexOf('rest')

    if (restIndex === -1 || restIndex >= pathParts.length - 1) {
      throw new Error(`Invalid REST path: ${pathname}`)
    }

    const category = pathParts[restIndex + 1]
    const subcategory = pathParts[restIndex + 2] // Undefined for category-only pages.

    const categoryData = await getRest(currentVersion, effectiveApiVersion, category)

    let operations: Operation[] = []

    if (subcategory && categoryData?.[subcategory]) {
      operations = categoryData[subcategory]
    } else if (category && categoryData) {
      // Categories without subcategories nest their operations one level deeper.
      operations = Object.values(categoryData).flat()
    }

    let manualContent = ''
    if (page.markdown) {
      const markerIndex = page.markdown.indexOf(
        '<!-- Content after this section is automatically generated -->',
      )
      if (markerIndex > 0) {
        const { content } = matter(page.markdown)
        const manualContentMarkerIndex = content.indexOf(
          '<!-- Content after this section is automatically generated -->',
        )
        if (manualContentMarkerIndex > 0) {
          const rawManualContent = content.substring(0, manualContentMarkerIndex).trim()
          if (rawManualContent) {
            manualContent = await renderContent(rawManualContent, {
              ...context,
              markdownRequested: true,
            })
          }
        }
      }
    }

    const templateData = await this.prepareTemplateData(
      page,
      operations,
      context,
      manualContent,
      effectiveApiVersion,
    )

    const templateContent = loadTemplate(this.templateName)

    // templateData replaces context.page, so the merged object is not a strict Context.
    const rendered = await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    } as unknown as Context)

    if (DEBUG) console.log(`[DEBUG] RestTransformer completed in ${Date.now() - startTime}ms`)
    return rendered
  }

  private async prepareTemplateData(
    page: Page,
    operations: Operation[],
    context: Context,
    manualContent: string,
    apiVersion?: string,
  ): Promise<PreparedTemplateData> {
    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    const preparedOperations = await Promise.all(
      operations.map(async (operation) => await this.prepareOperation(operation)),
    )

    // Identical response schemas render once per page; later endpoints link to the first operation.
    const slugger = new GithubSlugger()
    const titleToSlug = new Map<string, string>()
    for (const op of preparedOperations) {
      titleToSlug.set(op.title, slugger.slug(op.title))
    }
    const schemaMap = new Map<string, string>()
    for (const op of preparedOperations) {
      for (const example of op.codeExamples) {
        const schema = example.response?.schema
        if (!schema || typeof schema !== 'string') continue

        const existing = schemaMap.get(schema)
        if (existing && existing !== op.title) {
          const slug = titleToSlug.get(existing) || ''
          example.response.schema = `Same response schema as [${existing}](#${slug}).`
        } else if (!existing) {
          schemaMap.set(schema, op.title)
        }
      }
    }

    return {
      page: {
        title: page.title,
        intro,
      },
      manualContent,
      restOperations: preparedOperations,
      apiVersion,
    }
  }

  private async prepareOperation(operation: Operation): Promise<PreparedOperation> {
    const description = operation.descriptionHTML ? fastTextOnly(operation.descriptionHTML) : ''

    const needsContentTypeHeader = operation.subcategory === 'inference'
    const omitHeaders =
      operation.subcategory === 'management-console' || operation.subcategory === 'manage-ghes'
    const showHeaders = !omitHeaders

    const hasParameters =
      (operation.parameters?.length || 0) > 0 || (operation.bodyParameters?.length || 0) > 0

    const statusCodes = operation.statusCodes?.map((statusCode) => ({
      ...statusCode,
      description: statusCode.description ? fastTextOnly(statusCode.description) : undefined,
    }))

    const codeExamples =
      operation.codeExamples?.map((example) => {
        let url = `${operation.serverUrl}${operation.requestPath}`

        if (example.request?.parameters && Object.keys(example.request.parameters).length > 0) {
          for (const [key, value] of Object.entries(example.request.parameters)) {
            url = url.replace(`{${key}}`, String(value))
          }
        }

        const responseSchema = (
          example.response as { schema?: Parameters<typeof summarizeSchema>[0] } | undefined
        )?.schema
        return {
          request: {
            description: example.request?.description
              ? fastTextOnly(example.request.description)
              : '',
            url,
            acceptHeader: example.request?.acceptHeader,
            contentType: example.request?.contentType,
            needsContentTypeHeader: needsExplicitContentTypeHeader(example.request?.contentType),
            bodyParameters: getCurlBodyArguments(
              example.request?.bodyParameters,
              example.request?.contentType,
              { jsonIndent: 2 },
            ),
          },
          response: {
            statusCode: example.response?.statusCode,
            schema: responseSchema ? summarizeSchema(responseSchema) : null,
          },
        }
      }) || []

    return {
      ...operation,
      description,
      hasParameters,
      showHeaders,
      needsContentTypeHeader,
      statusCodes,
      codeExamples,
    }
  }
}
