import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { load } from 'js-yaml'
import path from 'path'
import { liquid } from '@/content-render/index'
import { allVersions } from '@/versions/lib/all-versions'
import { loadTemplate } from '@/article-api/lib/load-template'
import { stripHtmlComments } from '@/article-api/lib/strip-html-comments'
import { getSecretScanningData } from '@/secret-scanning/lib/get-secret-scanning-data'

export class SecretScanningTransformer implements PageTransformer {
  templateName = 'secret-scanning-page.template.md'

  canTransform(page: Page): boolean {
    return page.autogenerated === 'secret-scanning'
  }

  // Secret scanning output skips the final remark pass because page.render rewrites markdown links.
  // Later cleanup only creates fragment links such as #token-versions, which do not need rewriting.
  async transform(page: Page, _pathname: string, context: Context): Promise<string> {
    if (!context.secretScanningData) {
      const currentVersion = context.currentVersion
      if (!currentVersion) throw new Error('currentVersion is required')

      const isEnterpriseCloud = currentVersion.includes('cloud')
      const isEnterpriseServer = currentVersion.includes('enterprise-server')
      const versionPath = isEnterpriseCloud
        ? 'ghec'
        : isEnterpriseServer
          ? `ghes-${allVersions[currentVersion].currentRelease}`
          : 'fpt'

      const secretScanningDir = path.join(process.cwd(), 'src/secret-scanning/data/pattern-docs')
      const filepath = path.join(secretScanningDir, versionPath, 'public-docs.yml')

      try {
        const data = await getSecretScanningData(filepath)

        for (const entry of data) {
          // Resolve Liquid before YAML parses hasValidityCheck to match middleware behavior.
          if (typeof entry.hasValidityCheck === 'string' && entry.hasValidityCheck.includes('{%')) {
            entry.hasValidityCheck = load(
              await liquid.parseAndRender(entry.hasValidityCheck, context),
            ) as boolean
          }

          // Resolve Liquid before YAML parses hasExtendedMetadata to match middleware behavior.
          if (
            typeof entry.hasExtendedMetadata === 'string' &&
            entry.hasExtendedMetadata.includes('{%')
          ) {
            entry.hasExtendedMetadata = load(
              await liquid.parseAndRender(entry.hasExtendedMetadata, context),
            ) as boolean
          }

          if (entry.isduplicate) {
            entry.secretType += ' <br/><a href="#token-versions">Token versions</a>'
          }
        }

        context.secretScanningData = data
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
          context.secretScanningData = []
        } else {
          throw error
        }
      }
    }

    context.markdownRequested = true
    let content = await page.render(context)

    // Agent and crawler requests need the full table; React DataTable is absent in markdown mode.
    if (context.secretScanningData && context.secretScanningData.length > 0) {
      const bool = (v: unknown) => (v ? '✓' : '✗')
      const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|')
      // Convert isduplicate's <br/><a> HTML before later br cleanup splits secretType table cells.
      const cleanSecretType = (s: string) =>
        s
          .replace(
            / <br\/><a href="#token-versions">Token versions<\/a>/,
            ', [Token versions](#token-versions)',
          )
          .replace(/<br\s*\/?>/gi, ', ')
          .replace(/<a\s+href="([^"]*)"[^>]*>([^<]*)<\/a>/gi, '[$2]($1)')
          .replace(/<[^>]+>/g, '')
      const header =
        '| Provider | Secret | Secret type | Partner | User alert | Push protection | Validity check | Metadata | Base64 |'
      const separator = '| --- | --- | --- | :---: | :---: | :---: | :---: | :---: | :---: |'
      const rows = context.secretScanningData.map(
        (entry: Record<string, unknown>) =>
          `| ${escape(String(entry.provider))} | ${escape(String(entry.supportedSecret))} | ${escape(cleanSecretType(String(entry.secretType)))} | ${bool(entry.isPublic)} | ${bool(entry.isPrivateWithGhas)} | ${bool(entry.hasPushProtection)} | ${bool(entry.hasValidityCheck)} | ${bool(entry.hasExtendedMetadata)} | ${bool(entry.base64Supported)} |`,
      )
      const table = ['\n\n## Supported patterns\n', header, separator, ...rows].join('\n')
      content += table
    }

    content = stripHtmlComments(content)

    content = content.replace(/<span[^>]*aria-label="Supported"[^>]*>[^<]*<\/span>/g, '✓')
    content = content.replace(/<span[^>]*aria-label="Unsupported"[^>]*>[^<]*<\/span>/g, '✗')
    content = content.replace(/<br\s*\/?>/gi, '\n')
    content = content.replace(/<a\s+href="([^"]*)"[^>]*>([^<]*)<\/a>/gi, '[$2]($1)')
    // Repeat stripping handles nested tags like <scr<script>ipt>; the limit stops loops.
    let previous = ''
    let iterations = 0
    const MAX_STRIP_ITERATIONS = 10
    while (content !== previous && iterations < MAX_STRIP_ITERATIONS) {
      previous = content
      content = content.replace(/<[^>]+>/g, '')
      iterations++
    }

    content = content.replace(/\n{3,}/g, '\n\n').trim()

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    const templateContent = loadTemplate(this.templateName)
    return await liquid.parseAndRender(templateContent, {
      ...context,
      page: { title: page.title, intro },
      content,
    })
  }
}
