import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { renderContent } from '@/content-render/index'
import { fastTextOnly } from '@/content-render/unified/text-only'
import { loadTemplate } from '@/article-api/lib/load-template'
import matter from '@gr2m/gray-matter'

/**
 * Transformer for Webhooks pages.
 * Converts webhook events and payloads into markdown format using a Liquid template.
 */
export class WebhooksTransformer implements PageTransformer {
  templateName = 'webhooks-page.template.md'

  canTransform(page: Page): boolean {
    return page.autogenerated === 'webhooks'
  }

  async transform(page: Page, pathname: string, context: Context): Promise<string> {
    // Import getInitialPageWebhooks dynamically to avoid circular dependencies
    const { getInitialPageWebhooks } = await import('@/webhooks/lib/index')

    // Extract version from context
    const currentVersion = context.currentVersion!

    // Get the webhook data
    const webhooksData = await getInitialPageWebhooks(currentVersion)

    // Prepare page intro
    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    // Prepare manual content
    let manualContent = ''
    if (page.markdown) {
      const { content } = matter(page.markdown)
      const markerIndex = content.indexOf(
        '<!-- Content after this section is automatically generated -->',
      )

      if (markerIndex > 0) {
        const manualMarkdown = content.substring(0, markerIndex).trim()
        if (manualMarkdown) {
          manualContent = await renderContent(manualMarkdown, {
            ...context,
            markdownRequested: true,
          })
        }
      }
    }

    // Prepare webhooks data for template
    const preparedWebhooks = webhooksData.map((webhook) => ({
      name: webhook.name,
      actionTypes: webhook.actionTypes,
      summary: webhook.data.summaryHtml ? fastTextOnly(webhook.data.summaryHtml) : '',
      description: webhook.data.descriptionHtml ? fastTextOnly(webhook.data.descriptionHtml) : '',
      availability: webhook.data.availability || [],
      bodyParameters: (webhook.data.bodyParameters || []).map((param) => ({
        name: param.name || '',
        type: param.type || '',
        description: param.description
          ? fastTextOnly(param.description).replace(/\n/g, ' ').trim()
          : '',
        isRequired: param.isRequired || false,
      })),
      payloadExample: webhook.data.payloadExample
        ? JSON.stringify(webhook.data.payloadExample, null, 2)
        : null,
    }))

    // Prepare template data
    const templateData: Record<string, unknown> = {
      page: {
        title: page.title,
        intro,
      },
      manualContent,
      webhooks: preparedWebhooks,
    }

    // Load and render template
    const templateContent = loadTemplate(this.templateName)

    return await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })
  }
}
