import type { Context, Page } from '@/types'
import type { PageTransformer } from './types'
import { renderContent } from '@/content-render/index'
import { fastTextOnly } from '@/content-render/unified/text-only'
import { loadTemplate } from '@/article-api/lib/load-template'
import matter from '@gr2m/gray-matter'

export class WebhooksTransformer implements PageTransformer {
  templateName = 'webhooks-page.template.md'

  canTransform(page: Page): boolean {
    return page.autogenerated === 'webhooks'
  }

  async transform(page: Page, pathname: string, context: Context): Promise<string> {
    // Dynamic import avoids circular dependencies.
    const { getInitialPageWebhooks } = await import('@/webhooks/lib/index')

    const currentVersion = context.currentVersion!

    const webhooksData = await getInitialPageWebhooks(currentVersion)

    const intro = page.intro ? await page.renderProp('intro', context, { textOnly: true }) : ''

    let manualContent = ''
    if (page.markdown) {
      const { content } = matter(page.markdown)
      const markerIndex = content.indexOf(
        '<!-- Content after this section is automatically generated -->',
      )

      if (markerIndex > 0) {
        const manualMarkdown = content.substring(0, markerIndex).trim()
        if (manualMarkdown) {
          manualContent = await renderContent(manualMarkdown, {
            ...context,
            markdownRequested: true,
          })
        }
      }
    }

    // Omit payload examples so the generated webhook page stays compact.
    const preparedWebhooks = webhooksData.map((webhook) => ({
      name: webhook.name,
      actionTypes: webhook.actionTypes,
      summary: webhook.data.summaryHtml ? fastTextOnly(webhook.data.summaryHtml) : '',
      description: webhook.data.descriptionHtml ? fastTextOnly(webhook.data.descriptionHtml) : '',
      availability: webhook.data.availability || [],
      bodyParameters: (webhook.data.bodyParameters || []).map((param) => ({
        name: param.name || '',
        type: param.type || '',
        description: param.description
          ? fastTextOnly(param.description).replace(/\n/g, ' ').trim()
          : '',
        isRequired: param.isRequired || false,
      })),
    }))

    // Common body parameters appear in at least 60 percent of webhooks.
    const paramCounts = new Map<string, number>()
    for (const webhook of preparedWebhooks) {
      for (const param of webhook.bodyParameters) {
        paramCounts.set(param.name, (paramCounts.get(param.name) || 0) + 1)
      }
    }
    const threshold = preparedWebhooks.length * 0.6
    const commonParamNames = new Set(
      [...paramCounts.entries()].filter(([, count]) => count >= threshold).map(([name]) => name),
    )

    // Omit high-frequency body parameters from rows; summarize matches from the first webhook.
    const commonParams =
      preparedWebhooks[0]?.bodyParameters.filter((p: { name: string }) =>
        commonParamNames.has(p.name),
      ) || []
    for (const webhook of preparedWebhooks) {
      webhook.bodyParameters = webhook.bodyParameters.filter(
        (p: { name: string }) => !commonParamNames.has(p.name),
      )
    }

    const templateData: Record<string, unknown> = {
      page: {
        title: page.title,
        intro,
      },
      manualContent,
      webhooks: preparedWebhooks,
      commonParams,
    }

    const templateContent = loadTemplate(this.templateName)

    return await renderContent(templateContent, {
      ...context,
      ...templateData,
      markdownRequested: true,
    })
  }
}
