import assert from 'assert'
import path from 'path'
import fs from 'fs/promises'
import { stripOuterTag } from '@/frame/lib/strip-outer-tag'
import getApplicableVersions from '@/versions/lib/get-applicable-versions'
import generateRedirectsForPermalinks from '@/redirects/lib/permalinks'
import getEnglishHeadings from '@/languages/lib/get-english-headings'
import { getAlertTitles } from '@/languages/lib/get-alert-titles'
import Permalink from './permalink'
import { renderContent } from '@/content-render/index'

import { productMap } from '@/products/lib/all-products'
import slash from 'slash'
import readFileContents from './read-file-contents'

import getDocumentType from '@/events/lib/get-document-type'
import { allTools } from '@/tools/lib/all-tools'
import { renderContentWithFallback } from '@/languages/lib/render-with-fallback'
import { deprecated, supported } from '@/versions/lib/enterprise-server-releases'
import { allPlatforms } from '@/tools/lib/all-platforms'
import type { Context, FrontmatterVersions, FeaturedLinksExpanded } from '@/types'
import type { Product } from '@/products/lib/all-products'
import { createLogger } from '@/observability/logger'
const logger = createLogger(import.meta.url)

const isProduction = process.env.NODE_ENV === 'production'

// Product ID validation runs for every page, so a Set avoids repeated key extraction.
const productMapKeysAsSet = new Set(Object.keys(productMap))

type FrontmatterError = {
  reason: string
  message?: string
  filepath?: string
  property?: string
}

type ReadFileContentsResult = {
  data?: Record<string, unknown>
  content?: string
  errors?: FrontmatterError[]
}

type PageInitOptions = {
  languageCode: string
  relativePath: string
  basePath: string
}

type PageReadResult = PageInitOptions & {
  fullPath: string
  markdown: string
  frontmatterErrors?: FrontmatterError[]
  [key: string]: unknown
}

type RenderOptions = {
  preferShort?: boolean
  unwrap?: boolean
  textOnly?: boolean
  throwIfEmpty?: boolean
}

type CommunityRedirect = {
  name: string
  href: string
}

export class FrontmatterErrorsError extends Error {
  public frontmatterErrors: FrontmatterError[]

  constructor(message: string, frontmatterErrors: FrontmatterError[]) {
    super(message)
    this.frontmatterErrors = frontmatterErrors
  }
}

class Page {
  public title: string = ''
  public rawTitle: string = ''
  public shortTitle?: string
  public rawShortTitle?: string
  public intro: string = ''
  public rawIntro?: string
  public product?: string
  public rawProduct?: string
  public permissions?: string
  public rawPermissions?: string
  public versions: FrontmatterVersions = {}
  public showMiniToc?: boolean
  public hidden?: boolean
  public redirect_from?: string[]
  public introLinks?: Record<string, string>
  public rawIntroLinks?: Record<string, string>
  public carousels?: Record<string, string[]>
  public rawCarousels?: Record<string, string[]>
  public autogenerated?: string
  public featuredLinks?: FeaturedLinksExpanded
  public children?: string[]
  public layout?: string

  public languageCode!: string
  public relativePath!: string
  public basePath!: string
  public fullPath!: string
  public markdown!: string
  public mtime!: number
  public documentType: string
  public applicableVersions: string[]
  public permalinks: Permalink[]
  public communityRedirect?: CommunityRedirect
  public detectedPlatforms: string[] = []
  public includesPlatformSpecificContent: boolean = false
  public detectedTools: string[] = []
  public includesToolSpecificContent: boolean = false
  public allToolsParsed: typeof allTools = allTools
  public introPlainText?: string

  public render: (context: Context) => Promise<string>

  static async init(opts: PageInitOptions): Promise<Page | undefined> {
    const readResult = await Page.read(opts)
    if (!readResult) return
    return new Page(readResult)
  }

  static async read(opts: PageInitOptions): Promise<PageReadResult | false> {
    assert(opts.languageCode, 'languageCode is required')
    assert(opts.relativePath, 'relativePath is required')
    assert(opts.basePath, 'basePath is required')

    const relativePath = slash(opts.relativePath)
    const fullPath = slash(path.join(opts.basePath, relativePath))

    // Node recommends read-first error handling: https://nodejs.org/api/fs.html#fs_fs_exists_path_callback
    try {
      const {
        data,
        content,
        errors: frontmatterErrors,
      }: ReadFileContentsResult = await readFileContents(fullPath)

      // Production pins mtime because reloads only run in local development.
      const mtime = isProduction ? 1 : (await fs.stat(fullPath)).mtimeMs

      // Frontmatter-only pages have undefined content.
      let markdown = content || ''

      // __GHES_SUPPORTED__[n] and __GHES_DEPRECATED__[-n] keep fixture ranges stable across GHES releases.
      if (opts.basePath.split(path.sep).includes('fixtures')) {
        for (let i = 0; i < supported.length; i++) {
          const version: string = supported[i]
          markdown = markdown.replaceAll(`__GHES_SUPPORTED__[${i}]`, version)
          markdown = markdown.replaceAll(`__GHES_SUPPORTED__[-${supported.length - i}]`, version)
        }
        for (let i = 0; i < deprecated.length; i++) {
          const version: string = deprecated[i]
          markdown = markdown.replaceAll(`__GHES_DEPRECATED__[${i}]`, version)
          markdown = markdown.replaceAll(`__GHES_DEPRECATED__[-${deprecated.length - i}]`, version)
        }
      }

      return {
        ...opts,
        relativePath,
        fullPath,
        ...(data || {}),
        markdown,
        mtime,
        frontmatterErrors,
      } as PageReadResult
    } catch (err) {
      if (err instanceof Error && (err as NodeJS.ErrnoException).code === 'ENOENT') return false
      logger.error('Failed to read page file', { error: err, fullPath })
      return false
    }
  }

  constructor(opts: PageReadResult) {
    if (opts.frontmatterErrors && opts.frontmatterErrors.length) {
      logger.error('Frontmatter errors loading page', {
        errorCount: opts.frontmatterErrors.length,
        fullPath: opts.fullPath,
        frontmatterErrors: opts.frontmatterErrors,
      })
      throw new FrontmatterErrorsError(
        `${opts.frontmatterErrors.length} frontmatter errors in ${opts.fullPath}`,
        opts.frontmatterErrors,
      )
    }

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { frontmatterErrors: _, ...cleanOpts } = opts
    Object.assign(this, cleanOpts)

    // Raw frontmatter preserves Liquid for rendered properties.
    this.rawIntro = this.intro
    this.rawTitle = this.title
    this.rawShortTitle = this.shortTitle
    this.rawProduct = this.product
    this.rawPermissions = this.permissions
    this.rawIntroLinks = this.introLinks
    this.rawCarousels = this.carousels

    this.documentType = getDocumentType(this.relativePath)

    this.applicableVersions = getApplicableVersions(this.versions, this.fullPath)

    // Only English enforces parent product versions because translations lag product edits.
    if (this.languageCode === 'en') {
      // Child pages cannot claim versions outside their parent product.
      const versionsParentProductIsNotAvailableIn = this.applicableVersions
        // The homepage has no parent product.
        .filter(
          (availableVersion: string) =>
            this.parentProduct && !this.parentProduct.versions.includes(availableVersion),
        )

      if (versionsParentProductIsNotAvailableIn.length) {
        throw new Error(
          `\`versions\` frontmatter in ${this.fullPath} contains ${versionsParentProductIsNotAvailableIn}, which ${this.parentProduct?.id} product is not available in!`,
        )
      }
    }

    this.permalinks = Permalink.derive(
      this.languageCode,
      this.relativePath,
      this.title,
      this.applicableVersions,
    )

    // Standard index pages need children so navigation can build sidebars.
    if (this.relativePath.endsWith('index.md')) {
      if (!this.children && !/(search|early-access)\/.*index.md/.test(this.relativePath)) {
        if (this.layout !== 'journey-landing') {
          throw new Error(`${this.fullPath} must contain 'children' frontmatter.`)
        }
      }
    }

    if (!this.relativePath.endsWith('index.md')) {
      this.showMiniToc = this.showMiniToc === false ? this.showMiniToc : true
    }

    this.render = this._render.bind(this)

    return this
  }

  buildRedirects(): Record<string, string> {
    return generateRedirectsForPermalinks(this.permalinks, this.redirect_from || []) as Record<
      string,
      string
    >
  }

  get parentProductId(): string | null {
    // The top-level content directory defines the product ID.
    const id = this.relativePath.split('/')[0]

    // The root content/index.md page has no product.
    if (id === 'index.md') return null

    if (process.env.NODE_ENV !== 'test') {
      assert(productMapKeysAsSet.has(id), `page ${this.fullPath} has an invalid product ID: ${id}`)
    }

    return id
  }

  get parentProduct(): Product | undefined {
    const id = this.parentProductId
    return id ? productMap[id] : undefined
  }

  async renderTitle(
    context: Context,
    opts: RenderOptions = { preferShort: true },
  ): Promise<string> {
    return opts.preferShort && this.shortTitle
      ? this.renderProp('shortTitle', context, opts)
      : this.renderProp('title', context, opts)
  }

  private async _render(context: Context): Promise<string> {
    // English heading IDs keep translated links stable.
    if (this.languageCode !== 'en') {
      const englishHeadings = getEnglishHeadings(this, context)
      context.englishHeadings = englishHeadings
    }

    context.alertTitles = await getAlertTitles(this)

    this.intro = await renderContentWithFallback(this, 'rawIntro', context)
    this.introPlainText = await renderContentWithFallback(this, 'rawIntro', context, {
      textOnly: true,
    })
    this.title = await renderContentWithFallback(this, 'rawTitle', context, {
      textOnly: true,
      throwIfEmpty: true,
    })

    const html = await renderContentWithFallback(this, 'markdown', context)

    // Discussions, Sponsors, and Codespaces send feedback to their community category.
    if (
      this.parentProduct &&
      (this.parentProduct.id === 'discussions' ||
        this.parentProduct.id === 'sponsors' ||
        this.parentProduct.id === 'codespaces')
    ) {
      this.communityRedirect = {
        name: 'Provide GitHub Feedback',
        href: `https://github.com/community/community/discussions/categories/${this.parentProduct.id}`,
      }
    }

    // Product frontmatter can contain Liquid.
    if (this.rawProduct) {
      this.product = await renderContentWithFallback(this, 'rawProduct', context)
    }

    // Permissions frontmatter can contain Liquid.
    if (this.rawPermissions) {
      this.permissions = await renderContentWithFallback(this, 'rawPermissions', context)
    }

    // Intro links can contain Liquid that needs version rendering.
    if (this.rawIntroLinks) {
      const introLinks: Record<string, string> = {}
      for (const [rawKey, value] of Object.entries(this.rawIntroLinks)) {
        introLinks[rawKey] = await renderContent(value, context, {
          textOnly: true,
        })
      }

      this.introLinks = introLinks
    }

    // Layout and handleInvalidQuerystringValues share platform names.
    this.detectedPlatforms = allPlatforms.filter((platform: string) => {
      // Word boundaries match ghd-tool mac but not ghd-tool macos.
      const regex = new RegExp(`ghd-tool ${platform}\\b|platform-${platform}\\b`)
      return regex.test(html)
    })
    this.includesPlatformSpecificContent = this.detectedPlatforms.length > 0

    // Detected tool flags render tool switchers.
    this.detectedTools = Object.keys(allTools).filter((tool: string) => {
      // Word boundaries match ghd-tool jetbrain but not ghd-tool jetbrain_beta.
      const regex = new RegExp(`ghd-tool ${tool}\\b|tool-${tool}\\b`)
      return regex.test(html)
    })

    // Components and utilities need the full tool list alongside detected tools.
    this.allToolsParsed = allTools

    this.includesToolSpecificContent = this.detectedTools.length > 0

    return html
  }

  // Custom Liquid tags need one-off rendering for page properties.
  async renderProp(
    propName: string,
    context: Context,
    opts: RenderOptions = { unwrap: false },
  ): Promise<string> {
    let prop: string
    if (propName === 'title') {
      prop = 'rawTitle'
    } else if (propName === 'shortTitle') {
      prop = this.rawShortTitle ? 'rawShortTitle' : 'rawTitle'
    } else if (propName === 'intro') {
      prop = 'rawIntro'
    } else {
      prop = propName
    }

    const html = await renderContentWithFallback(this, prop, context, opts)

    if (!opts.unwrap) return html

    return stripOuterTag(html)
  }

  // Remove /articles and its suffix while keeping any language, version, and product prefix.
  // Example: /en/articles/foo becomes /en.
  static getHomepage(requestPath: string): string {
    return requestPath.replace(/\/articles.*/, '')
  }
}

export default Page
