#!/usr/bin/env bash

# [start-readme]
#
# This script is run on a writer's machine to begin developing Early Access content locally.
#
# [end-readme]

set -e

# Go up a directory
pushd .. > /dev/null

if [ -d "docs-early-access" ]; then
  echo "A 'docs-early-access' directory already exists!"
  popd > /dev/null
  exit 0
fi

# Clone the repo
git clone git@github.com:github/docs-early-access.git

# Go back to the previous working directory
popd > /dev/null

# Symlink the local docs-early-access repo into this repo
node script/early-access/symlink-from-local-repo.js -p ../docs-early-access

echo -e '\nDone!'