#!/usr/bin/env bash

# [start-readme]
#
# Installs/updates all dependencies necessary for the docs environment. Equivalent of `npm install`.
#
# [end-readme]

source script/check-for-node

npm install