#!/usr/bin/env bash

# [start-readme]
#
# List all the TODOs in our JavaScript files and stylesheets.
#
# [end-readme]

echo "JavaScript TODOs"
grep -R TODO . --include "*.js" --exclude-dir=node_modules

echo
echo
echo "Stylesheet TODOs"
grep -R TODO . --include "*.*css" --exclude-dir=node_modules