import { describe, expect, test, vi, beforeEach } from 'vitest'

import { SecretScanningTransformer } from '@/article-api/transformers/secret-scanning-transformer'
import shortVersionsMiddleware from '@/versions/middleware/short-versions'
import { allVersions } from '@/versions/lib/all-versions'
import enterpriseServerReleases from '@/versions/lib/enterprise-server-releases'
import { getSecretScanningData } from '@/secret-scanning/lib/get-secret-scanning-data'
import type { Context, ExtendedRequest, Page, SecretScanningData } from '@/types'

vi.mock('@/secret-scanning/lib/get-secret-scanning-data')
vi.mock('@/article-api/lib/load-template', () => ({
  loadTemplate: () => '{{ content }}',
}))

const ghesConditional = '{% ifversion ghes %}false{% else %}true{% endif %}'

const makeEntry = (): SecretScanningData =>
  ({
    provider: 'Example',
    supportedSecret: 'Example Token',
    secretType: 'example_token',
    versions: {},
    isPublic: true,
    isPrivateWithGhas: true,
    hasPushProtection: true,
    hasValidityCheck: ghesConditional,
    hasExtendedMetadata: ghesConditional,
    base64Supported: false,
    isduplicate: false,
  }) as SecretScanningData

const stubPage = {
  autogenerated: 'secret-scanning',
  title: 'Test',
  intro: '',
  render: vi.fn().mockResolvedValue(''),
  renderProp: vi.fn().mockResolvedValue(''),
} as unknown as Page

const buildContext = async (currentVersion: string): Promise<Context> => {
  const req = { language: 'en', query: {} } as ExtendedRequest
  req.context = { currentVersion, allVersions, enterpriseServerReleases } as Context
  req.context.currentVersionObj = allVersions[currentVersion]
  await shortVersionsMiddleware(req, null, () => {})
  return req.context
}

describe('SecretScanningTransformer Liquid evaluation', () => {
  const transformer = new SecretScanningTransformer()

  beforeEach(() => {
    vi.clearAllMocks()
  })

  const oldestGhes = enterpriseServerReleases.oldestSupported

  test('resolves GHES conditionals to false on enterprise-server', async () => {
    vi.mocked(getSecretScanningData).mockResolvedValue([makeEntry()])
    const context = await buildContext(`enterprise-server@${oldestGhes}`)

    await transformer.transform(stubPage, '/test', context)

    expect(context.secretScanningData).toBeDefined()
    expect(context.secretScanningData![0].hasValidityCheck).toBe(false)
    expect(context.secretScanningData![0].hasExtendedMetadata).toBe(false)
  })

  test('resolves GHES conditionals to true on free-pro-team', async () => {
    vi.mocked(getSecretScanningData).mockResolvedValue([makeEntry()])
    const context = await buildContext('free-pro-team@latest')

    await transformer.transform(stubPage, '/test', context)

    expect(context.secretScanningData).toBeDefined()
    expect(context.secretScanningData![0].hasValidityCheck).toBe(true)
    expect(context.secretScanningData![0].hasExtendedMetadata).toBe(true)
  })
})
