import fs from 'fs'
import path from 'path'
import matter from '@gr2m/gray-matter'
import { addError } from 'markdownlint-rule-helpers'

import { getFrontmatter } from '../helpers/utils'
import type { RuleParams, RuleErrorCallback } from '@/content-linter/types'

// Lazily computed list of valid category values from content/rest/index.md.
let validCategories: string[] | null = null

function getValidCategories(): string[] {
  if (validCategories) return validCategories

  const restIndexPath = path.resolve(process.env.ROOT || '.', 'content/rest/index.md')
  const content = fs.readFileSync(restIndexPath, 'utf-8')
  const { data } = matter(content)
  validCategories = (data.includedCategories as string[]) || []
  return validCategories
}

// Tests reset the cache when filesystem fixtures change.
export function resetCache(): void {
  validCategories = null
}

export const frontmatterRestApiCategory = {
  names: ['GHD067', 'frontmatter-rest-api-category'],
  description:
    'Autogenerated REST API endpoint files must have a valid `category` frontmatter property',
  tags: ['frontmatter', 'rest', 'category'],
  function: (params: RuleParams, onError: RuleErrorCallback) => {
    const filePath = params.name
    const rootDir = process.env.ROOT || '.'
    const restDir = path.resolve(rootDir, 'content/rest')

    // Resolve CWD-relative file paths and strings-mode keys before comparing them with content/rest.
    const resolved = path.isAbsolute(filePath) ? filePath : path.resolve(filePath)
    const relativePath = path.relative(restDir, resolved)

    if (relativePath.startsWith('..')) return

    // Index files are category-level pages, not endpoint pages.
    if (path.basename(resolved) === 'index.md') return

    const fm = getFrontmatter(params.lines)
    if (!fm) return

    if (fm.autogenerated !== 'rest') return

    // Missing category has no source line, so report at the frontmatter start.
    const categoryLineIndex = params.lines.findIndex((line) =>
      line.trimStart().startsWith('category'),
    )
    const fmOpenLine = params.lines.indexOf('---')
    const errorLine =
      categoryLineIndex !== -1 ? categoryLineIndex + 1 : fmOpenLine !== -1 ? fmOpenLine + 1 : 1

    if (!fm.category) {
      addError(
        onError,
        errorLine,
        'Missing `category` frontmatter. Autogenerated REST endpoint files must have a `category` property with a value from `content/rest/index.md` `includedCategories`.',
        undefined,
        undefined,
        undefined,
      )
      return
    }

    if (!Array.isArray(fm.category)) {
      addError(
        onError,
        errorLine,
        '`category` frontmatter must be an array.',
        undefined,
        undefined,
        undefined,
      )
      return
    }

    if (fm.category.length === 0) {
      addError(
        onError,
        errorLine,
        '`category` frontmatter must have at least one value.',
        undefined,
        undefined,
        undefined,
      )
      return
    }

    const valid = getValidCategories()
    for (const value of fm.category) {
      if (!valid.includes(value as string)) {
        addError(
          onError,
          errorLine,
          `Invalid category "${value}". Must be one of: ${valid.join(', ')}`,
          undefined,
          undefined,
          undefined,
        )
      }
    }
  },
}
