import fs from 'fs'
import path from 'path'
import matter from '@gr2m/gray-matter'
import { addError } from 'markdownlint-rule-helpers'

import { getFrontmatter } from '../helpers/utils'
import type { RuleParams, RuleErrorCallback } from '@/content-linter/types'

// Lazily computed list of valid category values from content/rest/index.md.
let validCategories: string[] | null = null

/**
 * Read the `includedCategories` frontmatter from content/rest/index.md.
 */
function getValidCategories(): string[] {
  if (validCategories) return validCategories

  const restIndexPath = path.resolve(process.env.ROOT || '.', 'content/rest/index.md')
  const content = fs.readFileSync(restIndexPath, 'utf-8')
  const { data } = matter(content)
  validCategories = (data.includedCategories as string[]) || []
  return validCategories
}

/**
 * Reset the cached valid categories. Exported so tests can call it
 * between test cases if the fixture changes.
 */
export function resetCache(): void {
  validCategories = null
}

export const frontmatterRestApiCategory = {
  names: ['GHD067', 'frontmatter-rest-api-category'],
  description:
    'Autogenerated REST API endpoint files must have a valid `category` frontmatter property',
  tags: ['frontmatter', 'rest', 'category'],
  function: (params: RuleParams, onError: RuleErrorCallback) => {
    const filePath = params.name
    const rootDir = process.env.ROOT || '.'
    const restDir = path.resolve(rootDir, 'content/rest')

    // Resolve the file path against CWD (markdownlint provides paths
    // relative to CWD when using `files`, or string keys when using `strings`).
    const resolved = path.isAbsolute(filePath) ? filePath : path.resolve(filePath)
    const relativePath = path.relative(restDir, resolved)

    // Skip files that aren't under content/rest/
    if (relativePath.startsWith('..')) return

    // Skip index files — they are category-level pages, not endpoint pages
    if (path.basename(resolved) === 'index.md') return

    const fm = getFrontmatter(params.lines)
    if (!fm) return

    // Only apply to autogenerated REST files
    if (fm.autogenerated !== 'rest') return

    // Find error line: prefer the category line, fall back to opening ---
    const categoryLineIndex = params.lines.findIndex((line) =>
      line.trimStart().startsWith('category'),
    )
    const fmOpenLine = params.lines.indexOf('---')
    const errorLine =
      categoryLineIndex !== -1 ? categoryLineIndex + 1 : fmOpenLine !== -1 ? fmOpenLine + 1 : 1

    // Check: category must exist
    if (!fm.category) {
      addError(
        onError,
        errorLine,
        'Missing `category` frontmatter. Autogenerated REST endpoint files must have a `category` property with a value from `content/rest/index.md` `includedCategories`.',
        undefined,
        undefined,
        undefined,
      )
      return
    }

    // Check: category must be an array
    if (!Array.isArray(fm.category)) {
      addError(
        onError,
        errorLine,
        '`category` frontmatter must be an array.',
        undefined,
        undefined,
        undefined,
      )
      return
    }

    // Check: category must have at least one value
    if (fm.category.length === 0) {
      addError(
        onError,
        errorLine,
        '`category` frontmatter must have at least one value.',
        undefined,
        undefined,
        undefined,
      )
      return
    }

    // Check: each value must be in the valid list
    const valid = getValidCategories()
    for (const value of fm.category) {
      if (!valid.includes(value as string)) {
        addError(
          onError,
          errorLine,
          `Invalid category "${value}". Must be one of: ${valid.join(', ')}`,
          undefined,
          undefined,
          undefined,
        )
      }
    }
  },
}
