import { addError, ellipsify } from 'markdownlint-rule-helpers'

import { getRange } from '@/content-linter/lib/helpers/utils'
import frontmatter from '@/frame/lib/read-frontmatter'

import type { RuleParams, RuleErrorCallback } from '@/content-linter/types'

// Order matters: longer phrases must come first to avoid partial matches.
const TERMINOLOGY_REPLACEMENTS: [string, string][] = [
  ['limited public beta', 'public preview'],
  ['public beta', 'public preview'],
  ['private beta', 'private preview'],
  ['beta', 'public preview'],

  ['alpha', 'private preview'],

  ['deprecation', 'closing down'],
  ['deprecated', 'closing down'],

  ['sunset', 'retired'],
]

// Exclude paths that use release-phase terms as legitimate content.
const EXCLUDED_PATHS: string[] = [
  'content/actions/reference/runners/github-hosted-runners.md',
  'content/actions/reference/workflows-and-actions/metadata-syntax.md',
  'content/admin/administering-your-instance/administering-your-instance-from-the-command-line/command-line-utilities.md',
  'content/authentication/managing-commit-signature-verification/checking-for-existing-gpg-keys.md',
  'content/codespaces/setting-your-user-preferences/choosing-the-stable-or-beta-host-image.md',
  'content/rest/using-the-rest-api/getting-started-with-the-rest-api.md',
  'data/reusables/actions/jobs/choosing-runner-github-hosted.md',
  'data/reusables/code-scanning/codeql-query-tables/cpp.md',
  'data/reusables/dependabot/dependabot-updates-supported-versioning-tags.md',
  'data/variables/release-phases.yml',
  'data/release-notes/enterprise-server/3-17/0-rc1.yml',
  'content/site-policy/',
  'data/features/',
  'data/release-notes/enterprise-server/3-14/',
  'data/release-notes/enterprise-server/3-15/',
]

interface CompiledRegex {
  regex: RegExp
  outdatedTerm: string
  replacement: string
}

interface MatchInfo {
  start: number
  end: number
  text: string
  replacement: string
  outdatedTerm: string
}

// Compile the regexes once instead of for every line.
const COMPILED_REGEXES: CompiledRegex[] = TERMINOLOGY_REPLACEMENTS.map(
  ([outdatedTerm, replacement]) => ({
    regex: new RegExp(`(?<!\\w|-|_)${outdatedTerm.replace(/\s+/g, '\\s+')}(?!\\w|-|_)`, 'gi'),
    outdatedTerm,
    replacement,
  }),
)

function findOutdatedTerminologyMatches(line: string): MatchInfo[] {
  const foundMatches: MatchInfo[] = []

  for (const { regex, outdatedTerm, replacement } of COMPILED_REGEXES) {
    // Global regexes retain lastIndex across calls, so reset it for each line.
    regex.lastIndex = 0
    let match: RegExpExecArray | null

    while ((match = regex.exec(line)) !== null) {
      const overlaps = foundMatches.some(
        (existing) =>
          (match!.index >= existing.start && match!.index < existing.end) ||
          (match!.index + match![0].length > existing.start &&
            match!.index + match![0].length <= existing.end) ||
          (match!.index <= existing.start && match!.index + match![0].length >= existing.end),
      )

      if (!overlaps) {
        foundMatches.push({
          start: match.index,
          end: match.index + match[0].length,
          text: match[0],
          replacement,
          outdatedTerm,
        })
      }
    }
  }

  return foundMatches.sort((a, b) => a.start - b.start)
}

export const outdatedReleasePhaseTerminology = {
  names: ['GHD046', 'outdated-release-phase-terminology'],
  description:
    'Outdated release phase terminology should be replaced with current GitHub terminology',
  tags: ['terminology', 'consistency', 'release-phases'],
  severity: 'error',
  function: (params: RuleParams, onError: RuleErrorCallback) => {
    for (const filepath of EXCLUDED_PATHS) {
      if (params.name.startsWith(filepath)) {
        return
      }
    }

    const frontmatterString = params.frontMatterLines.join('\n')
    const fm = frontmatter(frontmatterString).data
    if (fm && fm.autogenerated) return

    for (let i = 0; i < params.lines.length; i++) {
      const line = params.lines[i]
      const lineNumber = i + 1

      const foundMatches = findOutdatedTerminologyMatches(line)

      for (const matchInfo of foundMatches) {
        const range = getRange(line, matchInfo.text)
        const errorMessage = `Replace outdated terminology "${matchInfo.text}" with "${matchInfo.replacement}"`

        const fixInfo = {
          editColumn: matchInfo.start + 1,
          deleteCount: matchInfo.text.length,
          insertText: matchInfo.replacement,
        }

        addError(onError, lineNumber, errorMessage, ellipsify(line), range, fixInfo)
      }
    }
  },
}
