import type { BrokenLink } from '@/links/lib/link-report'

// Collected in pass 1; validated after the checker knows every page's heading IDs.
export interface PendingCrossPageAnchor {
  targetKey: string
  fragment: string
  href: string
  file: string
  line: number
  text?: string
}

// Cross-page anchor validation runs after pass 1 populates the per-page heading ID cache.
// Missing cache entries are skipped, not flagged: targets can resolve to an uncovered version
// or to autogenerated runtime anchors. The scheduled matrix does not cover every version.
// Anchors that only resolve in uncovered versions are not validated anywhere.
// Keep this pure so the two-pass behavior can be tested without rendering the whole site.
// The #top fragment works without a computed heading ID because browsers scroll to the top.
export function validateCrossPageAnchors(
  pendingCrossPageAnchors: PendingCrossPageAnchor[],
  headingIdsByPageKey: Map<string, Set<string>>,
): BrokenLink[] {
  const broken: BrokenLink[] = []
  for (const anchor of pendingCrossPageAnchors) {
    if (anchor.fragment === 'top') continue
    const targetHeadingIds = headingIdsByPageKey.get(anchor.targetKey)
    if (!targetHeadingIds) continue
    if (!targetHeadingIds.has(anchor.fragment)) {
      broken.push({
        href: anchor.href,
        file: anchor.file,
        lines: [anchor.line],
        text: anchor.text,
      })
    }
  }
  return broken
}
