import type { BrokenLink } from '@/links/lib/link-report'

/**
 * A cross-page anchor link (`/some/path#fragment`) collected during pass 1 of the
 * internal link checker, to be validated in pass 2 once every page's heading IDs are known.
 */
export interface PendingCrossPageAnchor {
  targetKey: string
  fragment: string
  href: string
  file: string
  line: number
  text?: string
}

/**
 * Pass 2 of cross-page anchor validation: given the collected cross-page anchor links
 * and the fully-populated per-page heading ID cache, return the links whose fragment is
 * missing from the target page.
 *
 * A target with no cache entry is skipped, not flagged. That happens when the target
 * resolves to a version not covered by the current run, or the target is an autogenerated
 * page whose anchors resolve at runtime. Note the scheduled matrix does not run every
 * version, so an anchor whose target only resolves to an uncovered version is currently
 * not validated anywhere: closing that gap is follow-up guardrail work. Kept as a pure
 * function so the two-pass behavior can be tested without rendering the whole site.
 *
 * `#top` is exempt, mirroring the same-page anchor check. Per the HTML spec a browser
 * scrolls to the top of the document for `#top` when nothing carries that ID, so it is
 * always valid and never appears in a page's computed heading IDs.
 */
export function validateCrossPageAnchors(
  pendingCrossPageAnchors: PendingCrossPageAnchor[],
  headingIdsByPageKey: Map<string, Set<string>>,
): BrokenLink[] {
  const broken: BrokenLink[] = []
  for (const anchor of pendingCrossPageAnchors) {
    if (anchor.fragment === 'top') continue
    const targetHeadingIds = headingIdsByPageKey.get(anchor.targetKey)
    if (!targetHeadingIds) continue
    if (!targetHeadingIds.has(anchor.fragment)) {
      broken.push({
        href: anchor.href,
        file: anchor.file,
        lines: [anchor.line],
        text: anchor.text,
      })
    }
  }
  return broken
}
