import type { Context, Page } from '@/types'
import { allVersions } from '@/versions/lib/all-versions'
import { getFeaturesByVersion } from '@/versions/middleware/features'
import { getDataByLanguage, getDeepDataByLanguage } from '@/data-directory/lib/get-data'
import {
  normalizeLinkPath,
  renderAndExtractLinks,
  resolveInternalLinkKey,
} from '@/links/lib/extract-links'
import { computeHeadingIds } from '@/links/lib/heading-anchors'

/**
 * Shared, version-aware helpers for validating that a `path#fragment` link lands on a
 * real heading of its target page. Kept neutral (no PR/CI specifics) so both the
 * scheduled internal checker and the PR-time gate can render a target page in a given
 * version and compute its heading anchor IDs the same way.
 */

// Explicit version prefix on a resolved pageMap key, e.g. the `enterprise-cloud@latest`
// in `/en/enterprise-cloud@latest/actions/foo`. `resolveInternalLinkKey` already maps
// `enterprise-server@latest` to the stable release, so `@latest` never appears for GHES.
const EXPLICIT_VERSION_RE =
  /^\/(?:[a-z]{2}(?:-[a-z]{2})?\/)?(free-pro-team@latest|enterprise-cloud@latest|enterprise-server@[0-9.]+)(?:\/|$)/

/**
 * Extract the version a resolved link key pins to, or null when the key carries no
 * explicit version segment (an unversioned link that inherits the source page's version).
 */
export function versionFromResolvedKey(key: string): string | null {
  const match = key.match(EXPLICIT_VERSION_RE)
  if (!match) return null
  return allVersions[match[1]] ? match[1] : null
}

/**
 * Line numbers (1-based) in `content` where a Markdown link points at exactly
 * `hrefWithFragment`.
 *
 * The destination must END at the match: a bare substring search is a prefix match, so
 * looking for `](/a#foo` would also hit `](/a#foobar)` and misreport that line. A Markdown
 * destination ends at `)` or at whitespace before an optional title.
 */
export function findLinkLines(content: string, hrefWithFragment: string): number[] {
  const needle = `](${hrefWithFragment}`
  const lines = content.split('\n')
  const found: number[] = []
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    for (let at = line.indexOf(needle); at !== -1; at = line.indexOf(needle, at + 1)) {
      const next = line[at + needle.length]
      if (next === undefined || next === ')' || /\s/.test(next)) {
        found.push(i + 1)
        break
      }
    }
  }
  return found
}

/**
 * Resolve a link href to a pageMap key, considering the version the source page is being
 * rendered in.
 *
 * `resolveInternalLinkKey` only tries the href as written. An unversioned href like
 * `/copilot/foo` written on a GHEC-only page has no `/en/copilot/foo` key in the pageMap
 * (that key only exists when the target applies to FPT), so resolution returns null and
 * the link is silently skipped. Retrying with the source version prefixed picks up those
 * targets so their anchors get checked too.
 */
export function resolveLinkKeyForVersion(
  href: string,
  version: string,
  pageMap: Record<string, Page>,
): string | null {
  const direct = resolveInternalLinkKey(href, pageMap)
  if (direct) return direct

  // Only worth retrying when the href carries no version of its own.
  const normalized = normalizeLinkPath(href)
  if (EXPLICIT_VERSION_RE.test(normalized)) return null

  const withoutLang = normalized.replace(/^\/[a-z]{2}(?:-[a-z]{2})?(?=\/|$)/, '')
  return resolveInternalLinkKey(`/${version}${withoutLang}`, pageMap)
}

/**
 * Whether a target page's heading anchors can be derived from its Markdown headings.
 *
 * Two page kinds compute their headings from data at runtime, not from static Markdown
 * headings, so `computeHeadingIds` can't see them and would report false positives:
 *  - `autogenerated` pages (REST/GraphQL/webhooks/audit-log-events): headings come from
 *    OpenAPI operation IDs / action prefixes.
 *  - the glossary page: headings come from a `{% for glossary in glossaries %}` loop over
 *    `data/glossaries/external.yml`, which isn't populated in this lightweight render.
 *
 * Links into these pages are skipped rather than flagged.
 */
export function isAnchorCheckableTarget(page: Page): boolean {
  if ((page as unknown as { autogenerated?: unknown }).autogenerated) return false
  const markdown = page.markdown
  if (
    typeof markdown === 'string' &&
    /\{%-?\s*for\s+\w+\s+in\s+glossaries\s*-?%\}/.test(markdown)
  ) {
    return false
  }
  return true
}

// Loaded once and shared: getDeepDataByLanguage walks the whole data/tables tree, which is
// far too expensive to repeat per page per version.
let tablesCache: Record<string, unknown> | null = null
function getTables(): Record<string, unknown> {
  if (!tablesCache) tablesCache = getDeepDataByLanguage('tables', 'en')
  return tablesCache
}

/**
 * Build a minimal per-version Liquid context for rendering a page's Markdown. Mirrors the
 * context the scheduled internal checker uses (version flags + feature flags), plus the
 * `variables` site data so `{% data variables.* %}` in headings resolves, and the `tables`
 * data so pages that generate headings from a `{% for %}` loop over a reference table
 * (e.g. `content/copilot/reference/copilot-feature-matrix.md`) produce their real heading
 * text instead of a literal `{{ groupName }}`, which would otherwise false-positive.
 */
export function buildRenderContext(
  page: Page,
  version: string,
  pageMap: Record<string, Page>,
  redirects: Record<string, string>,
): Context {
  const versionObj = allVersions[version]
  return {
    currentVersion: version,
    currentLanguage: 'en',
    currentVersionObj: versionObj,
    [versionObj.shortName]: true,
    site: getDataByLanguage('variables', 'en'),
    tables: getTables(),
    page,
    pages: pageMap,
    redirects,
    ...getFeaturesByVersion(version),
  } as unknown as Context
}

/**
 * Compute the set of heading anchor IDs for a page rendered in a specific version.
 * Results are memoized in the optional `cache` (keyed by version + relative path) so a
 * target referenced by many links is only rendered once per version.
 */
export async function getPageHeadingIds(
  page: Page,
  version: string,
  pageMap: Record<string, Page>,
  redirects: Record<string, string>,
  cache?: Map<string, Set<string>>,
): Promise<Set<string>> {
  const cacheKey = `${version}|${page.relativePath}`
  const cached = cache?.get(cacheKey)
  if (cached) return cached

  const context = buildRenderContext(page, version, pageMap, redirects)
  const { renderedMarkdown } = await renderAndExtractLinks(page.markdown, context)
  const ids = computeHeadingIds(renderedMarkdown)

  cache?.set(cacheKey, ids)
  return ids
}
