import type { Context, Page } from '@/types'
import { allVersions } from '@/versions/lib/all-versions'
import { getFeaturesByVersion } from '@/versions/middleware/features'
import { getDataByLanguage, getDeepDataByLanguage } from '@/data-directory/lib/get-data'
import {
  normalizeLinkPath,
  renderAndExtractLinks,
  resolveInternalLinkKey,
} from '@/links/lib/extract-links'
import { computeHeadingIds } from '@/links/lib/heading-anchors'

// Version-aware anchor helpers stay neutral so the scheduled checker and PR gate render
// target pages with the same version context and compute the same heading IDs.

// Matches explicit version prefixes on resolved pageMap keys such as
// /en/enterprise-cloud@latest/actions/foo. resolveInternalLinkKey maps
// enterprise-server@latest to the stable release, so @latest never appears for GHES.
const EXPLICIT_VERSION_RE =
  /^\/(?:[a-z]{2}(?:-[a-z]{2})?\/)?(free-pro-team@latest|enterprise-cloud@latest|enterprise-server@[0-9.]+)(?:\/|$)/

// Null means the key carries no explicit version and inherits the source page's version.
export function versionFromResolvedKey(key: string): string | null {
  const match = key.match(EXPLICIT_VERSION_RE)
  if (!match) return null
  return allVersions[match[1]] ? match[1] : null
}

// Find 1-based line numbers where a Markdown link points exactly at hrefWithFragment.
// The destination must end at the match; substring searches confuse /a#foo with /a#foobar.
// Markdown destinations end at ) or at whitespace before an optional title.
export function findLinkLines(content: string, hrefWithFragment: string): number[] {
  const needle = `](${hrefWithFragment}`
  const lines = content.split('\n')
  const found: number[] = []
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    for (let at = line.indexOf(needle); at !== -1; at = line.indexOf(needle, at + 1)) {
      const next = line[at + needle.length]
      if (next === undefined || next === ')' || /\s/.test(next)) {
        found.push(i + 1)
        break
      }
    }
  }
  return found
}

// Resolve hrefs in the source page's version so enterprise keys beat the /en key.
// The explicit retry handles hrefs with a language prefix, which resolveInternalLinkKey
// refuses to reinterpret as relative to a version.
export function resolveLinkKeyForVersion(
  href: string,
  version: string,
  pageMap: Record<string, Page>,
): string | null {
  const direct = resolveInternalLinkKey(href, pageMap, version)
  if (direct) return direct

  // Only worth retrying when the href carries no version of its own.
  const normalized = normalizeLinkPath(href)
  if (EXPLICIT_VERSION_RE.test(normalized)) return null

  const withoutLang = normalized.replace(/^\/[a-z]{2}(?:-[a-z]{2})?(?=\/|$)/, '')
  return resolveInternalLinkKey(`/${version}${withoutLang}`, pageMap)
}

// Some target pages compute headings from runtime data, not static Markdown headings.
// Autogenerated REST, GraphQL, webhook, and audit-log pages derive headings from data files.
// The glossary page loops over data/glossaries/external.yml, which lightweight renders skip.
// Links into these pages are skipped rather than flagged.
export function isAnchorCheckableTarget(page: Page): boolean {
  if ((page as unknown as { autogenerated?: unknown }).autogenerated) return false
  const markdown = page.markdown
  if (
    typeof markdown === 'string' &&
    /\{%-?\s*for\s+\w+\s+in\s+glossaries\s*-?%\}/.test(markdown)
  ) {
    return false
  }
  return true
}

// getDeepDataByLanguage walks the whole data/tables tree, which is too costly per page.
let tablesCache: Record<string, unknown> | null = null
function getTables(): Record<string, unknown> {
  if (!tablesCache) tablesCache = getDeepDataByLanguage('tables', 'en')
  return tablesCache
}

// Match the scheduled internal checker's version flags and feature flags.
// Include variables data so data tags in headings resolve, and tables data so reference-table
// loops such as content/copilot/reference/copilot-feature-matrix.md render real heading text.
export function buildRenderContext(
  page: Page,
  version: string,
  pageMap: Record<string, Page>,
  redirects: Record<string, string>,
): Context {
  const versionObj = allVersions[version]
  return {
    currentVersion: version,
    currentLanguage: 'en',
    currentVersionObj: versionObj,
    [versionObj.shortName]: true,
    site: getDataByLanguage('variables', 'en'),
    tables: getTables(),
    page,
    pages: pageMap,
    redirects,
    ...getFeaturesByVersion(version),
  } as unknown as Context
}

// Cache by version and relative path so repeated target links render only once per version.
export async function getPageHeadingIds(
  page: Page,
  version: string,
  pageMap: Record<string, Page>,
  redirects: Record<string, string>,
  cache?: Map<string, Set<string>>,
): Promise<Set<string>> {
  const cacheKey = `${version}|${page.relativePath}`
  const cached = cache?.get(cacheKey)
  if (cached) return cached

  const context = buildRenderContext(page, version, pageMap, redirects)
  const { renderedMarkdown } = await renderAndExtractLinks(page.markdown, context)
  const ids = computeHeadingIds(renderedMarkdown)

  cache?.set(cacheKey, ids)
  return ids
}
