/**
 * When `update-internal-links` rewrites a link's path via a redirect, the original
 * URL fragment (`#anchor`) is carried over from the old target. If the destination
 * page doesn't have that heading, the anchor is silently stale and lands the reader
 * at the top of the page.
 *
 * This validator renders the destination page through Liquid (once per version, cached)
 * and checks whether the anchor exists in the page's real heading IDs, so the caller
 * can decide whether to keep or drop the fragment.
 *
 * Correctness note: dropping a fragment is a destructive edit, so we only ever return
 * `'drop'` when the anchor is absent from EVERY applicable version's render. If we can't
 * render the page faithfully (render error, autogenerated page, unknown version), we
 * return `'unvalidatable'` so the caller keeps the fragment rather than risk a false drop.
 *
 * Towards github/docs-engineering#6738.
 */
import warmServer from '@/frame/lib/warm-server'
import { allVersions } from '@/versions/lib/all-versions'
import { getFeaturesByVersion } from '@/versions/middleware/features'
import { renderMarkdownLiquid } from '@/links/lib/extract-links'
import { computeHeadingIds } from '@/links/lib/heading-anchors'
import { createLogger } from '@/observability/logger'
import type { Context, Page } from '@/types'

const logger = createLogger(import.meta.url)

// 'keep'          → anchor exists in every applicable version → leave the fragment.
// 'drop'          → anchor is absent from every applicable version → safe to remove.
// 'mixed'         → anchor exists in some but not all versions → keep, but flag for review.
// 'unvalidatable' → couldn't faithfully render the destination → keep, don't risk a drop.
export type FragmentDecision = 'keep' | 'drop' | 'mixed' | 'unvalidatable'

export class RedirectedFragmentValidator {
  private headingIdCache = new Map<string, Set<string> | null>()
  private warmPromise: Promise<unknown> | null = null

  constructor(
    private pages: Record<string, Page>,
    private redirects: Record<string, string>,
    private language = 'en',
  ) {}

  // Rendering a page's Liquid faithfully (e.g. `{% data variables.x %}` inside a heading)
  // depends on the site data being loaded. Warm it lazily so callers that never hit a
  // redirected fragment don't pay the cost.
  private ensureWarmed(): Promise<unknown> {
    if (!this.warmPromise) {
      this.warmPromise = warmServer([this.language])
    }
    return this.warmPromise
  }

  // Overridable in tests so the decision logic can be exercised without rendering.
  protected async headingIdsFor(page: Page, version: string): Promise<Set<string> | null> {
    const cacheKey = `${version}\u0000${page.relativePath}`
    const cached = this.headingIdCache.get(cacheKey)
    if (cached !== undefined) return cached

    let ids: Set<string> | null = null
    try {
      const versionObj = allVersions[version]
      if (!versionObj) {
        this.headingIdCache.set(cacheKey, null)
        return null
      }
      await this.ensureWarmed()
      const context = {
        currentVersion: version,
        currentLanguage: this.language,
        currentVersionObj: versionObj,
        [versionObj.shortName]: true,
        pages: this.pages,
        redirects: this.redirects,
        page,
        ...getFeaturesByVersion(version),
      } as unknown as Context
      // Use renderMarkdownLiquid, NOT renderAndExtractLinks: the latter swallows Liquid
      // render failures and falls back to the raw markdown, which would yield heading IDs
      // computed from unrendered `{% data %}` expressions. Those never match a real anchor,
      // so classify() would return 'drop' and destructively delete a valid fragment. Here a
      // render failure throws, lands in the catch below, and becomes 'unvalidatable'.
      const renderedMarkdown = await renderMarkdownLiquid(page.markdown, context)
      ids = computeHeadingIds(renderedMarkdown)
    } catch (error) {
      logger.warn('Failed to render destination page for fragment validation', {
        page: page.relativePath,
        version,
        error: error instanceof Error ? error.message : String(error),
      })
      ids = null
    }
    this.headingIdCache.set(cacheKey, ids)
    return ids
  }

  /**
   * Decide what to do with a fragment carried over onto a redirected destination page.
   * `fragment` may include the leading `#`.
   */
  async classify(destPage: Page | undefined, fragment: string): Promise<FragmentDecision> {
    // Can't find the destination page (redirect to an archived/external target, or a
    // lookup miss) → we have nothing to validate against, so keep the fragment.
    if (!destPage) return 'unvalidatable'

    // Autogenerated pages (REST, GraphQL, webhooks) build their headings from data files
    // at render time in a way `computeHeadingIds` on the source markdown can't see, so we
    // can't reliably tell whether the anchor exists. Keep it and let the human/checker decide.
    if (destPage.autogenerated) return 'unvalidatable'

    const anchor = fragment.replace(/^#/, '')
    if (!anchor) return 'keep'

    // `#top` is always valid: per the HTML spec a browser scrolls to the top of the
    // document when nothing carries that ID, so it never appears in computed heading IDs
    // and would otherwise always classify as 'drop'. Mirrors the same-page anchor check
    // in check-links-internal.ts, which skips `#` and `#top`.
    if (anchor === 'top') return 'keep'

    const versions = destPage.applicableVersions || []
    if (versions.length === 0) return 'unvalidatable'

    let presentCount = 0
    for (const version of versions) {
      const ids = await this.headingIdsFor(destPage, version)
      // If even one applicable version fails to render, don't risk a destructive drop.
      if (ids === null) return 'unvalidatable'
      if (ids.has(anchor)) presentCount++
    }

    if (presentCount === versions.length) return 'keep'
    if (presentCount === 0) return 'drop'
    return 'mixed'
  }
}
