// update-internal-links carries URL fragments across redirect path rewrites.
// If the destination lacks the old heading, the stale fragment sends readers to the page top.
// Renders each applicable destination version through Liquid, with caching,
// and checks the fragment against real heading IDs before the caller keeps or drops it.
// Dropping a fragment is destructive, so drop only when every applicable version lacks it.
// Render errors, autogenerated pages, and unknown versions stay unvalidatable to avoid false drops.
import warmServer from '@/frame/lib/warm-server'
import { allVersions } from '@/versions/lib/all-versions'
import { getFeaturesByVersion } from '@/versions/middleware/features'
import { renderMarkdownLiquid } from '@/links/lib/extract-links'
import { computeHeadingIds } from '@/links/lib/heading-anchors'
import { createLogger } from '@/observability/logger'
import type { Context, Page } from '@/types'

const logger = createLogger(import.meta.url)

// keep means the anchor exists in every applicable version, so leave the fragment.
// drop means the anchor is absent from every applicable version, so removal is safe.
// mixed means some versions have the anchor and some do not, so keep it and flag review.
// unvalidatable means faithful rendering failed, so keep the fragment.
export type FragmentDecision = 'keep' | 'drop' | 'mixed' | 'unvalidatable'

export class RedirectedFragmentValidator {
  private headingIdCache = new Map<string, Set<string> | null>()
  private warmPromise: Promise<unknown> | null = null

  constructor(
    private pages: Record<string, Page>,
    private redirects: Record<string, string>,
    private language = 'en',
  ) {}

  // Faithful Liquid rendering needs site data, so warm lazily only for redirected fragments.
  private ensureWarmed(): Promise<unknown> {
    if (!this.warmPromise) {
      this.warmPromise = warmServer([this.language])
    }
    return this.warmPromise
  }

  // Tests override headingIdsFor so decision cases avoid rendering.
  // Use renderMarkdownLiquid, not renderAndExtractLinks, to avoid raw fallback false drops.
  protected async headingIdsFor(page: Page, version: string): Promise<Set<string> | null> {
    const cacheKey = `${version}\u0000${page.relativePath}`
    const cached = this.headingIdCache.get(cacheKey)
    if (cached !== undefined) return cached

    let ids: Set<string> | null = null
    try {
      const versionObj = allVersions[version]
      if (!versionObj) {
        this.headingIdCache.set(cacheKey, null)
        return null
      }
      await this.ensureWarmed()
      const context = {
        currentVersion: version,
        currentLanguage: this.language,
        currentVersionObj: versionObj,
        [versionObj.shortName]: true,
        pages: this.pages,
        redirects: this.redirects,
        page,
        ...getFeaturesByVersion(version),
      } as unknown as Context
      const renderedMarkdown = await renderMarkdownLiquid(page.markdown, context)
      ids = computeHeadingIds(renderedMarkdown)
    } catch (error) {
      logger.warn('Failed to render destination page for fragment validation', {
        page: page.relativePath,
        version,
        error: error instanceof Error ? error.message : String(error),
      })
      ids = null
    }
    this.headingIdCache.set(cacheKey, ids)
    return ids
  }

  // fragment can include the leading # from the redirected link.
  async classify(destPage: Page | undefined, fragment: string): Promise<FragmentDecision> {
    // Keep fragments for missing destination pages because no heading set exists.
    if (!destPage) return 'unvalidatable'

    // Autogenerated REST, GraphQL, and webhook pages build headings from data at render time.
    if (destPage.autogenerated) return 'unvalidatable'

    const anchor = fragment.replace(/^#/, '')
    if (!anchor) return 'keep'

    // #top mirrors check-links-internal.ts: browsers scroll to the top when no element has it.
    if (anchor === 'top') return 'keep'

    const versions = destPage.applicableVersions || []
    if (versions.length === 0) return 'unvalidatable'

    let presentCount = 0
    for (const version of versions) {
      const ids = await this.headingIdsFor(destPage, version)
      // Any render failure keeps the fragment, avoiding a destructive drop.
      if (ids === null) return 'unvalidatable'
      if (ids.has(anchor)) presentCount++
    }

    if (presentCount === versions.length) return 'keep'
    if (presentCount === 0) return 'drop'
    return 'mixed'
  }
}
