/**
 * PR Link Checker
 *
 * Fast validation of internal links in changed files.
 * Designed to run in <10 minutes on typical PRs.
 *
 * Usage:
 *   npm run check-links-pr
 *   npm run check-links-pr -- --files content/actions/index.md content/repos/index.md
 *
 * Environment variables:
 *   FILES_CHANGED - JSON array of changed files (from GitHub Actions)
 *   GITHUB_TOKEN - For posting PR comments
 *   ACTION_RUN_URL - Link to the action run
 *   SHOULD_COMMENT - Whether to post PR comments (default: false)
 *   FAIL_ON_FLAW - Exit with error code if broken links found (default: true)
 */

import { program } from 'commander'
import chalk from 'chalk'

import warmServer from '@/frame/lib/warm-server'
import {
  extractLinksWithLiquid,
  renderAndExtractLinks,
  createLiquidContext,
  checkInternalLink,
  checkAssetLink,
  isAssetLink,
  getRelativePath,
} from '@/links/lib/extract-links'
import {
  buildRenderContext,
  findLinkLines,
  getPageHeadingIds,
  isAnchorCheckableTarget,
  resolveLinkKeyForVersion,
  versionFromResolvedKey,
} from '@/links/lib/page-anchors'
import {
  type BrokenLink,
  type CrossPageAnchorFlaw,
  generatePRComment,
  groupBrokenLinks,
} from '@/links/lib/link-report'
import { uploadArtifact } from '@/links/scripts/upload-artifact'
import github from '@/workflows/github'
import { getActionContext } from '@/workflows/action-context'
import type { Page } from '@/types'
import fs from 'fs'
import path from 'path'

interface CheckResult {
  file: string
  brokenLinks: BrokenLink[]
  redirectLinks: BrokenLink[]
  totalLinksChecked: number
}

/**
 * Check all internal links in a single file
 */
async function checkFile(
  filePath: string,
  pageMap: Record<string, Page>,
  redirects: Record<string, string>,
  version: string = 'free-pro-team@latest',
  language: string = 'en',
): Promise<CheckResult> {
  const brokenLinks: BrokenLink[] = []
  const redirectLinks: BrokenLink[] = []
  let totalLinksChecked = 0

  // Read file content
  let content: string
  try {
    content = fs.readFileSync(filePath, 'utf-8')
  } catch {
    console.warn(`Could not read file: ${filePath}`)
    return { file: filePath, brokenLinks, redirectLinks, totalLinksChecked }
  }

  // Create context for Liquid rendering
  const context = createLiquidContext(version, language)

  // Extract links after Liquid rendering
  const { internalLinks } = await extractLinksWithLiquid(content, context)

  // Check each internal link (exclude imageLinks - they're static assets, not docs pages)
  totalLinksChecked = internalLinks.length

  for (const link of internalLinks) {
    // Check if this is an asset link (images, etc.) - verify file exists on disk
    if (isAssetLink(link.href)) {
      if (!checkAssetLink(link.href)) {
        brokenLinks.push({
          href: link.href,
          file: getRelativePath(filePath),
          lines: [link.line],
          text: link.text,
          isAutotitle: link.isAutotitle,
        })
      }
      continue
    }

    const result = checkInternalLink(link.href, pageMap, redirects)

    if (!result.exists) {
      brokenLinks.push({
        href: link.href,
        file: getRelativePath(filePath),
        lines: [link.line],
        text: link.text,
        isAutotitle: link.isAutotitle,
      })
    } else if (result.isRedirect) {
      redirectLinks.push({
        href: link.href,
        file: getRelativePath(filePath),
        lines: [link.line],
        text: link.text,
        isAutotitle: link.isAutotitle,
        isRedirect: true,
        redirectTarget: result.redirectTarget,
      })
    }
  }

  return { file: filePath, brokenLinks, redirectLinks, totalLinksChecked }
}

/**
 * Validate cross-page anchor links (`/path#fragment`) in a changed source page.
 *
 * Unlike the page-existence checks above (which run in a single version), anchors are
 * checked in every version the source page renders in, because a version-gated link or a
 * version-specific heading can be broken in one version and fine in another. For each
 * link with a fragment we resolve the target page, pick the version the link points to
 * (an explicit `/enterprise-*` prefix, else the source version), render that target on
 * demand, and confirm the fragment matches a real heading. Autogenerated and glossary
 * targets are skipped (their anchors aren't static Markdown headings).
 */
async function checkFileAnchors(
  filePath: string,
  sourcePage: Page,
  pageMap: Record<string, Page>,
  redirects: Record<string, string>,
  headingCache: Map<string, Set<string>>,
): Promise<CrossPageAnchorFlaw[]> {
  let content: string
  try {
    content = fs.readFileSync(filePath, 'utf-8')
  } catch {
    return []
  }

  const file = getRelativePath(filePath)
  const versions = sourcePage.applicableVersions ?? []
  // Resolve each broken link to its stable source line(s) from the raw markdown. Rendered
  // line numbers drift between versions (ifversion blocks expand differently), so keying on
  // them would report the same occurrence multiple times; the raw source line is stable.
  const rawLinesFor = (hrefWithFragment: string): number[] =>
    findLinkLines(content, hrefWithFragment)

  // Dedupe by target (file + href#fragment), aggregating the versions it breaks in.
  const flaws = new Map<
    string,
    { href: string; file: string; lines: number[]; text?: string; versionSet: Set<string> }
  >()

  for (const version of versions) {
    const context = buildRenderContext(sourcePage, version, pageMap, redirects)
    const { result } = await renderAndExtractLinks(content, context)

    for (const link of result.internalLinks) {
      if (!link.fragment) continue
      // `#top` is always valid: browsers scroll to the top of the document when nothing
      // carries that ID, so it never appears in computed heading IDs. Mirrors the
      // same-page checker in check-links-internal.ts, which skips `#` and `#top`.
      if (link.fragment === 'top') continue

      // resolveLinkKeyForVersion only returns direct (non-redirect) page hits, so
      // redirects, archived versions, and broken paths fall out here — they're not
      // anchor-scope flaws. Unversioned hrefs are retried against the version the source
      // page is currently rendered in, so GHEC/GHES-only targets resolve too.
      const targetKey = resolveLinkKeyForVersion(link.href, version, pageMap)
      if (!targetKey) continue
      const targetPage = pageMap[targetKey]
      if (!targetPage) continue

      // Check the target in the version the link points to: an explicit version prefix if
      // present, otherwise the version the source page is currently rendered in.
      const checkVersion = versionFromResolvedKey(targetKey) ?? version
      if (!targetPage.applicableVersions?.includes(checkVersion)) continue
      if (!isAnchorCheckableTarget(targetPage)) continue

      const headingIds = await getPageHeadingIds(
        targetPage,
        checkVersion,
        pageMap,
        redirects,
        headingCache,
      )
      if (headingIds.has(link.fragment)) continue

      const href = `${link.href}#${link.fragment}`
      const existing = flaws.get(href)
      if (existing) {
        existing.versionSet.add(checkVersion)
      } else {
        // Fall back to the rendered line when the raw scan misses (e.g. a version-idiom
        // href like `/{% ifversion %}...{% endif %}path` that isn't a literal string).
        const lines = rawLinesFor(href)
        flaws.set(href, {
          href,
          file,
          lines: lines.length ? lines : [link.line],
          text: link.text,
          versionSet: new Set([checkVersion]),
        })
      }
    }
  }

  return [...flaws.values()].map(({ versionSet, ...flaw }) => ({
    ...flaw,
    versions: [...versionSet].sort(),
  }))
}

function getChangedFiles(cliFiles?: string[]): string[] {
  // CLI args take precedence
  if (cliFiles && cliFiles.length > 0) {
    return cliFiles
  }

  // Check environment variable (from GitHub Actions)
  const filesChanged = process.env.FILES_CHANGED
  if (filesChanged) {
    // Try parsing as JSON first
    try {
      const parsed = JSON.parse(filesChanged)
      if (Array.isArray(parsed)) {
        return parsed
      }
    } catch {
      // Not JSON, treat as space-separated string (tj-actions/changed-files format)
      return filesChanged.split(/\s+/).filter(Boolean)
    }
  }

  return []
}

/**
 * Filter to only content/data files that might contain links
 */
function filterContentFiles(files: string[]): string[] {
  return files.filter((file) => {
    // Only check Markdown files in content/ or data/
    if (!file.endsWith('.md')) return false
    // Skip README.md files. They're developer docs, not published pages, and use
    // repo-relative paths (e.g. /src/...) that aren't valid site links.
    if (file === 'README.md' || file.endsWith('/README.md')) return false
    if (file.startsWith('content/') || file.startsWith('data/')) return true
    return false
  })
}

/**
 * Post a comment on the PR with broken link results
 */
async function commentOnPR(
  brokenLinks: BrokenLink[],
  brokenAnchors: CrossPageAnchorFlaw[],
  actionUrl?: string,
) {
  const token = process.env.GITHUB_TOKEN
  if (!token) {
    console.warn('No GITHUB_TOKEN, skipping PR comment')
    return
  }

  const actionContext = getActionContext()
  const { owner, repo } = actionContext
  const pullNumber = actionContext.pull_request?.number

  if (!owner || !repo || !pullNumber) {
    console.warn('Not in PR context, skipping comment')
    return
  }

  const octokit = github()
  const comment = generatePRComment(brokenLinks, {
    actionUrl,
    brokenAnchors,
    anchorsBlocking: process.env.FAIL_ON_ANCHOR_FLAW === 'true',
  })

  // Find any existing comment we previously posted (identified by the hidden marker)
  const marker = '<!-- link-checker-pr-comment -->'
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: pullNumber,
  })
  const existingComment = comments.find((c) => c.body?.includes(marker))

  if (!comment) {
    console.log('No broken links to report')
    // Links are now clean: remove any stale comment from an earlier commit.
    // Best-effort: a concurrent run may have already deleted it (404), and
    // cleanup should never turn an otherwise-passing run into a failure.
    if (existingComment) {
      try {
        await octokit.rest.issues.deleteComment({
          owner,
          repo,
          comment_id: existingComment.id,
        })
        console.log(`Deleted stale PR comment: ${existingComment.id}`)
      } catch (err) {
        console.warn(`Could not delete stale PR comment ${existingComment.id}:`, err)
      }
    }
    return
  }

  if (existingComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: existingComment.id,
      body: comment,
    })
    console.log(`Updated PR comment: ${existingComment.id}`)
  } else {
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: pullNumber,
      body: comment,
    })
    console.log(`Created PR comment on #${pullNumber}`)
  }
}

/**
 * Main entry point
 */
async function main() {
  program
    .name('check-links-pr')
    .description('Check internal links in changed files')
    .option('-f, --files <files...>', 'Files to check (overrides FILES_CHANGED env)')
    .option('--all', 'Check all content files (for testing)')
    .option('--verbose', 'Verbose output')
    .parse()

  const options = program.opts()
  const startTime = Date.now()

  console.log(chalk.blue('🔗 PR Link Checker'))
  console.log('')

  // Get files to check
  let files = getChangedFiles(options.files)

  if (options.all) {
    // For testing: check all content files (limited)
    const glob = await import('glob')
    files = glob.sync('content/**/*.md').slice(0, 50)
    console.log(`Checking ${files.length} files (--all mode, limited to 50)`)
  } else if (files.length === 0) {
    console.log('No files to check. Exiting.')
    process.exit(0)
  }

  // Filter to content files only
  const contentFiles = filterContentFiles(files)
  if (contentFiles.length === 0) {
    console.log('No content files in changed files. Exiting.')
    process.exit(0)
  }

  console.log(`Checking ${contentFiles.length} file(s)...`)

  // Load page data
  console.log('Loading page data...')
  const { pages: pageMap, pageList, redirects } = await warmServer(['en'])
  console.log(
    `Loaded ${Object.keys(pageMap).length} pages, ${Object.keys(redirects).length} redirects`,
  )

  // Index en pages by their content-relative path so a changed file can be matched to its
  // Page (needed to know which versions to check its anchors in).
  const pageByRelativePath = new Map<string, Page>()
  for (const page of pageList) {
    if (page.languageCode === 'en') pageByRelativePath.set(page.relativePath, page)
  }

  // Cross-page anchor checking renders target pages on demand; the cache dedupes that
  // work across links and files (keyed by version + target path).
  const checkAnchors = process.env.CHECK_ANCHORS !== 'false'
  const headingCache = new Map<string, Set<string>>()

  // Check each file
  const allBrokenLinks: BrokenLink[] = []
  const allRedirectLinks: BrokenLink[] = []
  const allBrokenAnchors: CrossPageAnchorFlaw[] = []
  let totalLinksChecked = 0

  for (const file of contentFiles) {
    const filePath = path.resolve(file)
    if (!fs.existsSync(filePath)) {
      console.warn(`File not found: ${file}`)
      continue
    }

    if (options.verbose) {
      console.log(`  Checking: ${file}`)
    }

    const result = await checkFile(filePath, pageMap, redirects)
    allBrokenLinks.push(...result.brokenLinks)
    allRedirectLinks.push(...result.redirectLinks)
    totalLinksChecked += result.totalLinksChecked

    // Anchor validation only applies to published pages (data/ reusables have no versions
    // of their own), so skip any changed file that isn't a Page.
    const sourcePage = pageByRelativePath.get(getRelativePath(filePath))
    if (checkAnchors && sourcePage) {
      allBrokenAnchors.push(
        ...(await checkFileAnchors(filePath, sourcePage, pageMap, redirects, headingCache)),
      )
    }
  }

  // Report results
  const duration = ((Date.now() - startTime) / 1000).toFixed(1)
  console.log('')
  console.log(chalk.blue(`Checked ${totalLinksChecked} links in ${duration}s`))

  if (
    allBrokenLinks.length === 0 &&
    allRedirectLinks.length === 0 &&
    allBrokenAnchors.length === 0
  ) {
    console.log(chalk.green('✅ All links valid!'))
    // Remove any stale comment posted on an earlier commit, now that links are clean
    if (process.env.SHOULD_COMMENT === 'true') {
      try {
        await commentOnPR([], [], process.env.ACTION_RUN_URL)
      } catch (err) {
        console.warn('Could not clean up stale PR comment:', err)
      }
    }
    process.exit(0)
  }

  // Group and display results
  if (allBrokenLinks.length > 0) {
    console.log('')
    console.log(chalk.red(`❌ ${allBrokenLinks.length} broken link(s):`))
    const grouped = groupBrokenLinks(allBrokenLinks)
    for (const group of grouped) {
      console.log(`  ${chalk.yellow(group.target)}`)
      for (const occ of group.occurrences) {
        console.log(`    - ${occ.file}:${occ.lines.join(',')}`)
      }
    }
  }

  if (allRedirectLinks.length > 0) {
    console.log('')
    console.log(chalk.yellow(`⚠️  ${allRedirectLinks.length} redirect(s) to update:`))
    const grouped = groupBrokenLinks(allRedirectLinks)
    for (const group of grouped) {
      const target = group.occurrences[0]?.redirectTarget || '?'
      console.log(`  ${chalk.yellow(group.target)} → ${chalk.green(target)}`)
      for (const occ of group.occurrences) {
        console.log(`    - ${occ.file}:${occ.lines.join(',')}`)
      }
    }
  }

  if (allBrokenAnchors.length > 0) {
    console.log('')
    console.log(chalk.yellow(`⚓ ${allBrokenAnchors.length} broken cross-page anchor(s):`))
    for (const anchor of allBrokenAnchors) {
      console.log(
        `  ${chalk.yellow(anchor.href)}  (${anchor.versions.join(', ')})\n    - ${anchor.file}:${anchor.lines.join(',')}`,
      )
    }
  }

  // Write artifact for debugging. Best-effort: a reporting/API failure must
  // never fail the build. Only broken links (below) should fail the PR.
  const allFlaws = [...allBrokenLinks, ...allRedirectLinks]
  try {
    await uploadArtifact('broken-links.json', JSON.stringify(groupBrokenLinks(allFlaws), null, 2))
    if (allBrokenAnchors.length > 0) {
      await uploadArtifact('broken-anchors.json', JSON.stringify(allBrokenAnchors, null, 2))
    }
  } catch (err) {
    console.warn('Could not upload broken-links artifact:', err)
  }

  // Post PR comment if configured. Best-effort for the same reason.
  const shouldComment = process.env.SHOULD_COMMENT === 'true'
  if (shouldComment) {
    const actionUrl = process.env.ACTION_RUN_URL
    try {
      await commentOnPR(allFlaws, allBrokenAnchors, actionUrl)
    } catch (err) {
      console.warn('Could not post PR comment:', err)
    }
  }

  // Exit with error if broken links found. Broken page links block by default; cross-page
  // anchors are non-blocking during rollout unless FAIL_ON_ANCHOR_FLAW is explicitly set,
  // so we can measure false positives before turning them into a hard gate.
  const failOnFlaw = process.env.FAIL_ON_FLAW !== 'false'
  const failOnAnchorFlaw = process.env.FAIL_ON_ANCHOR_FLAW === 'true'
  const shouldFail =
    (failOnFlaw && allBrokenLinks.length > 0) || (failOnAnchorFlaw && allBrokenAnchors.length > 0)
  if (shouldFail) {
    console.log('')
    if (failOnFlaw && allBrokenLinks.length > 0) {
      console.log(chalk.red('Failing due to broken links'))
    }
    if (failOnAnchorFlaw && allBrokenAnchors.length > 0) {
      console.log(chalk.red('Failing due to broken cross-page anchors'))
    }
    process.exit(1)
  }
}

// Run if invoked directly
;(async () => {
  try {
    await main()
  } catch (err: unknown) {
    console.error('Fatal error:', err)
    process.exit(1)
  }
})()
