---
secrets:
  DOCS_BOT_PAT_BASE:
    key: DOCS_BOT_PAT_BASE
    type: github_pat
    owner: docs-engineering
    playbook: ''
    externally_usable: true
    kind: latest_at_deployment_start
  DOCS_BOT_APP_CLIENT_ID:
    owner: docs-engineering
    type: github_app
    externally_usable: false
    playbook: ''
    kind: latest_at_deployment_start
  DOCS_BOT_APP_ID:
    owner: docs-engineering
    type: github_app
    externally_usable: false
    playbook: ''
    kind: latest_at_deployment_start
  DOCS_BOT_APP_PRIVATE_KEY:
    owner: docs-engineering
    type: github_app
    externally_usable: false
    playbook: ''
    kind: latest_at_deployment_start
