name: docs-internal Moda CI

# More info on CI actions setup:
# https://docs.github.com/en/actions

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'gh-readonly-queue/**'
  merge_group:
    types: [checks_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
