name: Site policy sync

# **What it does**: Creates a branch in our site-policy repo with changes to site policy docs.
# **Why we have it**: We want to keep the site-policy repo up to date.
# **Who does it impact**: site-policy-admins and Developer Policy teams.

# Controls when the action will run.
on:
  # Triggers the workflow pull requests merged to the main branch
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'content/site-policy/**'
      - '.github/workflows/site-policy-sync.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    name: Get the latest docs
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.repository == 'github/docs-internal')
    runs-on: ubuntu-latest
    steps:
      - name: checkout docs-internal
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.DOCS_BOT_APP_ID }}
          private-key: ${{ secrets.DOCS_BOT_APP_PRIVATE_KEY }}
          owner: github
          repositories: site-policy

      - name: checkout public site-policy
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: github/site-policy
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: ''
          path: public-repo

      - name: Commits internal policies to copy of public repo with descriptive message from triggering PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          cd public-repo
          git config --local user.name 'site-policy-bot'
          git config --local user.email 'site-policy-bot@github.com'
          rm -rf Policies
          cp -r ../content/site-policy Policies
          git status
          git checkout -b automated-sync-$GITHUB_RUN_ID
          git add .
          echo PR_TITLE: $PR_TITLE
          [[ ! -z $PR_TITLE ]] && DESCRIPTION="${PR_TITLE}" || DESCRIPTION="Update manually triggered by workflow"
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
          git commit -m "$(echo $DESCRIPTION)"

      - name: If there are changes to push, create a branch in the public repo and push changes
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cd public-repo
          git config --local user.name 'site-policy-bot'
          git config --local user.email 'site-policy-bot@github.com'
          NUM_FILES_CHANGED=$(git diff --name-only HEAD^..HEAD | wc -l)
          if [[ $NUM_FILES_CHANGED -ge 1 ]]
            then
              git push --set-upstream origin automated-sync-$GITHUB_RUN_ID
            else
              echo "No updates to push to the public repo"
          fi
