name: Triage new pull requests

# Labels opened or reopened public docs pull requests for triage.

on:
  # pull_request_target lets PRs from forks be triaged.
  pull_request_target:
    types:
      - reopened
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_pulls:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/node-npm-setup

      - name: Label new pull requests with 'triage'
        uses: ./.github/actions/labeler
        with:
          addLabels: 'triage'
