name: Triage new issues

# Labels opened or reopened public docs issues for triage and team assignment.

on:
  issues:
    types:
      - reopened
      - opened

permissions:
  contents: read
  issues: write

jobs:
  triage_issues:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/node-npm-setup

      - name: Label new issues with 'triage'
        uses: ./.github/actions/labeler
        with:
          addLabels: 'triage'
